#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationManagement.Model.CounterSupply
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GasStationManagement")]
	public partial class DataClassesCounterSupplyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_CounterSupply(TBL_CounterSupply instance);
    partial void UpdateTBL_CounterSupply(TBL_CounterSupply instance);
    partial void DeleteTBL_CounterSupply(TBL_CounterSupply instance);
    #endregion
		
		public DataClassesCounterSupplyDataContext() : 
				base(global::GasStationManagement.Model.Properties.Settings.Default.GasStationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCounterSupplyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCounterSupplyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCounterSupplyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCounterSupplyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_CounterSupply> TBL_CounterSupplies
		{
			get
			{
				return this.GetTable<TBL_CounterSupply>();
			}
		}
		
		public System.Data.Linq.Table<VW_CounterSupply> VW_CounterSupplies
		{
			get
			{
				return this.GetTable<VW_CounterSupply>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CounterSupplyDelete")]
		public int SP_CounterSupplyDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Counter_Id", DbType="Int")] System.Nullable<int> counter_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CounterSerialNo", DbType="VarChar(50)")] string counterSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), counter_Id, counterSerialNo, msgRet);
			msgRet = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CounterSupplyInsert")]
		public int SP_CounterSupplyInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Counter_Id", DbType="Int")] System.Nullable<int> counter_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CounterSerialNo", DbType="VarChar(50)")] string counterSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplyDate", DbType="VarChar(10)")] string supplyDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="BigInt")] System.Nullable<long> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InitialVc", DbType="VarChar(50)")] string initialVc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), counter_Id, counterSerialNo, supplyDate, price, initialVc, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CounterSupplyUpdate")]
		public int SP_CounterSupplyUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Counter_Id", DbType="Int")] System.Nullable<int> counter_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CounterSerialNo", DbType="VarChar(50)")] string counterSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplyDate", DbType="VarChar(10)")] string supplyDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="BigInt")] System.Nullable<long> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InitialVc", DbType="VarChar(50)")] string initialVc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), counter_Id, counterSerialNo, supplyDate, price, initialVc, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CounterSupply")]
	public partial class TBL_CounterSupply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Counter_Id;
		
		private string _CounterSerialNo;
		
		private string _SupplyDate;
		
		private System.Nullable<long> _Price;
		
		private string _InitialVc;
		
		private short _Suppliers_Id;
		
		private string _Description;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCounter_IdChanging(int value);
    partial void OnCounter_IdChanged();
    partial void OnCounterSerialNoChanging(string value);
    partial void OnCounterSerialNoChanged();
    partial void OnSupplyDateChanging(string value);
    partial void OnSupplyDateChanged();
    partial void OnPriceChanging(System.Nullable<long> value);
    partial void OnPriceChanged();
    partial void OnInitialVcChanging(string value);
    partial void OnInitialVcChanged();
    partial void OnSuppliers_IdChanging(short value);
    partial void OnSuppliers_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public TBL_CounterSupply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Counter_Id
		{
			get
			{
				return this._Counter_Id;
			}
			set
			{
				if ((this._Counter_Id != value))
				{
					this.OnCounter_IdChanging(value);
					this.SendPropertyChanging();
					this._Counter_Id = value;
					this.SendPropertyChanged("Counter_Id");
					this.OnCounter_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterSerialNo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CounterSerialNo
		{
			get
			{
				return this._CounterSerialNo;
			}
			set
			{
				if ((this._CounterSerialNo != value))
				{
					this.OnCounterSerialNoChanging(value);
					this.SendPropertyChanging();
					this._CounterSerialNo = value;
					this.SendPropertyChanged("CounterSerialNo");
					this.OnCounterSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SupplyDate
		{
			get
			{
				return this._SupplyDate;
			}
			set
			{
				if ((this._SupplyDate != value))
				{
					this.OnSupplyDateChanging(value);
					this.SendPropertyChanging();
					this._SupplyDate = value;
					this.SendPropertyChanged("SupplyDate");
					this.OnSupplyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialVc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InitialVc
		{
			get
			{
				return this._InitialVc;
			}
			set
			{
				if ((this._InitialVc != value))
				{
					this.OnInitialVcChanging(value);
					this.SendPropertyChanging();
					this._InitialVc = value;
					this.SendPropertyChanged("InitialVc");
					this.OnInitialVcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this.OnSuppliers_IdChanging(value);
					this.SendPropertyChanging();
					this._Suppliers_Id = value;
					this.SendPropertyChanged("Suppliers_Id");
					this.OnSuppliers_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_CounterSupply")]
	public partial class VW_CounterSupply
	{
		
		private int _Counter_Id;
		
		private string _CounterSerialNo;
		
		private string _SupplyDate;
		
		private System.Nullable<long> _Price;
		
		private string _InitialVc;
		
		private short _Suppliers_Id;
		
		private string _Description;
		
		private System.Nullable<bool> _IsActive;
		
		private string _Name;
		
		private string _Address;
		
		private string _Tel;
		
		private string _Brand;
		
		private double _Size;
		
		private string _Class;
		
		private int _Grate;
		
		private int _CalibrationDuration;
		
		public VW_CounterSupply()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter_Id", DbType="Int NOT NULL")]
		public int Counter_Id
		{
			get
			{
				return this._Counter_Id;
			}
			set
			{
				if ((this._Counter_Id != value))
				{
					this._Counter_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterSerialNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CounterSerialNo
		{
			get
			{
				return this._CounterSerialNo;
			}
			set
			{
				if ((this._CounterSerialNo != value))
				{
					this._CounterSerialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SupplyDate
		{
			get
			{
				return this._SupplyDate;
			}
			set
			{
				if ((this._SupplyDate != value))
				{
					this._SupplyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialVc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InitialVc
		{
			get
			{
				return this._InitialVc;
			}
			set
			{
				if ((this._InitialVc != value))
				{
					this._InitialVc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this._Suppliers_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this._Brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Float NOT NULL")]
		public double Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="VarChar(50)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this._Class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grate", DbType="Int NOT NULL")]
		public int Grate
		{
			get
			{
				return this._Grate;
			}
			set
			{
				if ((this._Grate != value))
				{
					this._Grate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalibrationDuration", DbType="Int NOT NULL")]
		public int CalibrationDuration
		{
			get
			{
				return this._CalibrationDuration;
			}
			set
			{
				if ((this._CalibrationDuration != value))
				{
					this._CalibrationDuration = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
