#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationManagement.Model.EVCDSupply
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GasStationManagement")]
	public partial class DataClassesEVCDSupplyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_EVCDSupply(TBL_EVCDSupply instance);
    partial void UpdateTBL_EVCDSupply(TBL_EVCDSupply instance);
    partial void DeleteTBL_EVCDSupply(TBL_EVCDSupply instance);
    #endregion
		
		public DataClassesEVCDSupplyDataContext() : 
				base(global::GasStationManagement.Model.Properties.Settings.Default.GasStationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesEVCDSupplyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesEVCDSupplyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesEVCDSupplyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesEVCDSupplyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_EVCDSupply> TBL_EVCDSupplies
		{
			get
			{
				return this.GetTable<TBL_EVCDSupply>();
			}
		}
		
		public System.Data.Linq.Table<VW_EVCDSupply> VW_EVCDSupplies
		{
			get
			{
				return this.GetTable<VW_EVCDSupply>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EVCDSupplyDelete")]
		public int SP_EVCDSupplyDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVCD_Id", DbType="Int")] System.Nullable<int> eVCD_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVCDSerialNo", DbType="VarChar(50)")] string eVCDSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eVCD_Id, eVCDSerialNo, msgRet);
			msgRet = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EVCDSupplyInsert")]
		public int SP_EVCDSupplyInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVCD_Id", DbType="Int")] System.Nullable<int> eVCD_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVCDSerialNo", DbType="VarChar(50)")] string eVCDSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplyDate", DbType="VarChar(10)")] string supplyDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="BigInt")] System.Nullable<long> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InitialVm", DbType="BigInt")] System.Nullable<long> initialVm, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TEVCDSerialNo", DbType="VarChar(50)")] string tEVCDSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PEVCDSerialNo", DbType="VarChar(50)")] string pEVCDSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eVCD_Id, eVCDSerialNo, supplyDate, price, initialVm, tEVCDSerialNo, pEVCDSerialNo, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EVCDSupplyUpdate")]
		public int SP_EVCDSupplyUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVCD_Id", DbType="Int")] System.Nullable<int> eVCD_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVCDSerialNo", DbType="VarChar(50)")] string eVCDSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplyDate", DbType="VarChar(10)")] string supplyDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="BigInt")] System.Nullable<long> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InitialVm", DbType="BigInt")] System.Nullable<long> initialVm, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TEVCDSerialNo", DbType="VarChar(50)")] string tEVCDSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PEVCDSerialNo", DbType="VarChar(50)")] string pEVCDSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eVCD_Id, eVCDSerialNo, supplyDate, price, initialVm, tEVCDSerialNo, pEVCDSerialNo, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_EVCDSupply")]
	public partial class TBL_EVCDSupply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EVCD_Id;
		
		private string _EVCDSerialNo;
		
		private string _SupplyDate;
		
		private System.Nullable<long> _Price;
		
		private long _InitialVm;
		
		private string _TEVCDSerialNo;
		
		private string _PEVCDSerialNo;
		
		private short _Suppliers_Id;
		
		private string _Description;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEVCD_IdChanging(int value);
    partial void OnEVCD_IdChanged();
    partial void OnEVCDSerialNoChanging(string value);
    partial void OnEVCDSerialNoChanged();
    partial void OnSupplyDateChanging(string value);
    partial void OnSupplyDateChanged();
    partial void OnPriceChanging(System.Nullable<long> value);
    partial void OnPriceChanged();
    partial void OnInitialVmChanging(long value);
    partial void OnInitialVmChanged();
    partial void OnTEVCDSerialNoChanging(string value);
    partial void OnTEVCDSerialNoChanged();
    partial void OnPEVCDSerialNoChanging(string value);
    partial void OnPEVCDSerialNoChanged();
    partial void OnSuppliers_IdChanging(short value);
    partial void OnSuppliers_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public TBL_EVCDSupply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVCD_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EVCD_Id
		{
			get
			{
				return this._EVCD_Id;
			}
			set
			{
				if ((this._EVCD_Id != value))
				{
					this.OnEVCD_IdChanging(value);
					this.SendPropertyChanging();
					this._EVCD_Id = value;
					this.SendPropertyChanged("EVCD_Id");
					this.OnEVCD_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVCDSerialNo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EVCDSerialNo
		{
			get
			{
				return this._EVCDSerialNo;
			}
			set
			{
				if ((this._EVCDSerialNo != value))
				{
					this.OnEVCDSerialNoChanging(value);
					this.SendPropertyChanging();
					this._EVCDSerialNo = value;
					this.SendPropertyChanged("EVCDSerialNo");
					this.OnEVCDSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SupplyDate
		{
			get
			{
				return this._SupplyDate;
			}
			set
			{
				if ((this._SupplyDate != value))
				{
					this.OnSupplyDateChanging(value);
					this.SendPropertyChanging();
					this._SupplyDate = value;
					this.SendPropertyChanged("SupplyDate");
					this.OnSupplyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialVm", DbType="BigInt NOT NULL")]
		public long InitialVm
		{
			get
			{
				return this._InitialVm;
			}
			set
			{
				if ((this._InitialVm != value))
				{
					this.OnInitialVmChanging(value);
					this.SendPropertyChanging();
					this._InitialVm = value;
					this.SendPropertyChanged("InitialVm");
					this.OnInitialVmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEVCDSerialNo", DbType="VarChar(50)")]
		public string TEVCDSerialNo
		{
			get
			{
				return this._TEVCDSerialNo;
			}
			set
			{
				if ((this._TEVCDSerialNo != value))
				{
					this.OnTEVCDSerialNoChanging(value);
					this.SendPropertyChanging();
					this._TEVCDSerialNo = value;
					this.SendPropertyChanged("TEVCDSerialNo");
					this.OnTEVCDSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEVCDSerialNo", DbType="VarChar(50)")]
		public string PEVCDSerialNo
		{
			get
			{
				return this._PEVCDSerialNo;
			}
			set
			{
				if ((this._PEVCDSerialNo != value))
				{
					this.OnPEVCDSerialNoChanging(value);
					this.SendPropertyChanging();
					this._PEVCDSerialNo = value;
					this.SendPropertyChanged("PEVCDSerialNo");
					this.OnPEVCDSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this.OnSuppliers_IdChanging(value);
					this.SendPropertyChanging();
					this._Suppliers_Id = value;
					this.SendPropertyChanged("Suppliers_Id");
					this.OnSuppliers_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_EVCDSupply")]
	public partial class VW_EVCDSupply
	{
		
		private int _EVCD_Id;
		
		private string _EVCDSerialNo;
		
		private string _SupplyDate;
		
		private System.Nullable<long> _Price;
		
		private long _InitialVm;
		
		private string _TEVCDSerialNo;
		
		private string _PEVCDSerialNo;
		
		private short _Suppliers_Id;
		
		private string _Description;
		
		private System.Nullable<bool> _IsActive;
		
		private string _Name;
		
		private string _Address;
		
		private string _Tel;
		
		private string _Model;
		
		private string _Brand;
		
		public VW_EVCDSupply()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVCD_Id", DbType="Int NOT NULL")]
		public int EVCD_Id
		{
			get
			{
				return this._EVCD_Id;
			}
			set
			{
				if ((this._EVCD_Id != value))
				{
					this._EVCD_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVCDSerialNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EVCDSerialNo
		{
			get
			{
				return this._EVCDSerialNo;
			}
			set
			{
				if ((this._EVCDSerialNo != value))
				{
					this._EVCDSerialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SupplyDate
		{
			get
			{
				return this._SupplyDate;
			}
			set
			{
				if ((this._SupplyDate != value))
				{
					this._SupplyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialVm", DbType="BigInt NOT NULL")]
		public long InitialVm
		{
			get
			{
				return this._InitialVm;
			}
			set
			{
				if ((this._InitialVm != value))
				{
					this._InitialVm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEVCDSerialNo", DbType="VarChar(50)")]
		public string TEVCDSerialNo
		{
			get
			{
				return this._TEVCDSerialNo;
			}
			set
			{
				if ((this._TEVCDSerialNo != value))
				{
					this._TEVCDSerialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEVCDSerialNo", DbType="VarChar(50)")]
		public string PEVCDSerialNo
		{
			get
			{
				return this._PEVCDSerialNo;
			}
			set
			{
				if ((this._PEVCDSerialNo != value))
				{
					this._PEVCDSerialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this._Suppliers_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this._Brand = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
