#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationManagement.Model.StationMonitoringStateParameters
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GasStationManagement")]
	public partial class DataClassesStationMonitoringStateParametersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_StationMonitoringStateParameter(TBL_StationMonitoringStateParameter instance);
    partial void UpdateTBL_StationMonitoringStateParameter(TBL_StationMonitoringStateParameter instance);
    partial void DeleteTBL_StationMonitoringStateParameter(TBL_StationMonitoringStateParameter instance);
    #endregion
		
		public DataClassesStationMonitoringStateParametersDataContext() : 
				base(global::GasStationManagement.Model.Properties.Settings.Default.GasStationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateParametersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateParametersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateParametersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateParametersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_StationMonitoringStateParameter> VW_StationMonitoringStateParameters
		{
			get
			{
				return this.GetTable<VW_StationMonitoringStateParameter>();
			}
		}
		
		public System.Data.Linq.Table<TBL_StationMonitoringStateParameter> TBL_StationMonitoringStateParameters
		{
			get
			{
				return this.GetTable<TBL_StationMonitoringStateParameter>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_StationMonitoringStateParametersDelete")]
		public int SP_StationMonitoringStateParametersDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_StationMonitoringStateParametersInsert")]
		public int SP_StationMonitoringStateParametersInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StationMonitoringState_Id", DbType="Int")] System.Nullable<int> stationMonitoringState_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Parameters_Id", DbType="Int")] System.Nullable<int> parameters_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, stationMonitoringState_Id, parameters_Id, description, msgRet);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_StationMonitoringStateParametersUpdate")]
		public int SP_StationMonitoringStateParametersUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StationMonitoringState_Id", DbType="Int")] System.Nullable<int> stationMonitoringState_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Parameters_Id", DbType="Int")] System.Nullable<int> parameters_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, stationMonitoringState_Id, parameters_Id, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_StationMonitoringStateParametersDeleteWithSMSId")]
		public int SP_StationMonitoringStateParametersDeleteWithSMSId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StationMonitoringState_Id", DbType="Int")] System.Nullable<int> stationMonitoringState_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), stationMonitoringState_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_StationMonitoringStateParameters")]
	public partial class VW_StationMonitoringStateParameter
	{
		
		private int _Id;
		
		private int _StationMonitoringState_Id;
		
		private int _Parameters_Id;
		
		private string _Description;
		
		private string _MonitoringSysExeDate;
		
		private string _ChangeStateDate;
		
		private string _GasStationCode;
		
		private string _GasStationName;
		
		private string _GasStationBuildingDate;
		
		private int _Capacity;
		
		private string _ScheduleRegInfoStr;
		
		private short _ScheduleRegInfo;
		
		private System.Nullable<int> _ScheduleSpecPeriod;
		
		private int _RanFew;
		
		private System.Nullable<int> _Heater_Few;
		
		private string _GasStationTypeName;
		
		private string _WorkingPressureName;
		
		private string _UseTypeName;
		
		private string _LineName;
		
		private string _StationLinkTypeName;
		
		private string _SupplierName;
		
		private string _SupplierAddress;
		
		private string _SupplierTel;
		
		private string _ParametersName;
		
		public VW_StationMonitoringStateParameter()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationMonitoringState_Id", DbType="Int NOT NULL")]
		public int StationMonitoringState_Id
		{
			get
			{
				return this._StationMonitoringState_Id;
			}
			set
			{
				if ((this._StationMonitoringState_Id != value))
				{
					this._StationMonitoringState_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parameters_Id", DbType="Int NOT NULL")]
		public int Parameters_Id
		{
			get
			{
				return this._Parameters_Id;
			}
			set
			{
				if ((this._Parameters_Id != value))
				{
					this._Parameters_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysExeDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MonitoringSysExeDate
		{
			get
			{
				return this._MonitoringSysExeDate;
			}
			set
			{
				if ((this._MonitoringSysExeDate != value))
				{
					this._MonitoringSysExeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStateDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ChangeStateDate
		{
			get
			{
				return this._ChangeStateDate;
			}
			set
			{
				if ((this._ChangeStateDate != value))
				{
					this._ChangeStateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GasStationCode
		{
			get
			{
				return this._GasStationCode;
			}
			set
			{
				if ((this._GasStationCode != value))
				{
					this._GasStationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GasStationName
		{
			get
			{
				return this._GasStationName;
			}
			set
			{
				if ((this._GasStationName != value))
				{
					this._GasStationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationBuildingDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GasStationBuildingDate
		{
			get
			{
				return this._GasStationBuildingDate;
			}
			set
			{
				if ((this._GasStationBuildingDate != value))
				{
					this._GasStationBuildingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Int NOT NULL")]
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this._Capacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleRegInfoStr", DbType="VarChar(8)")]
		public string ScheduleRegInfoStr
		{
			get
			{
				return this._ScheduleRegInfoStr;
			}
			set
			{
				if ((this._ScheduleRegInfoStr != value))
				{
					this._ScheduleRegInfoStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleRegInfo", DbType="SmallInt NOT NULL")]
		public short ScheduleRegInfo
		{
			get
			{
				return this._ScheduleRegInfo;
			}
			set
			{
				if ((this._ScheduleRegInfo != value))
				{
					this._ScheduleRegInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleSpecPeriod", DbType="Int")]
		public System.Nullable<int> ScheduleSpecPeriod
		{
			get
			{
				return this._ScheduleSpecPeriod;
			}
			set
			{
				if ((this._ScheduleSpecPeriod != value))
				{
					this._ScheduleSpecPeriod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanFew", DbType="Int NOT NULL")]
		public int RanFew
		{
			get
			{
				return this._RanFew;
			}
			set
			{
				if ((this._RanFew != value))
				{
					this._RanFew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heater_Few", DbType="Int")]
		public System.Nullable<int> Heater_Few
		{
			get
			{
				return this._Heater_Few;
			}
			set
			{
				if ((this._Heater_Few != value))
				{
					this._Heater_Few = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationTypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GasStationTypeName
		{
			get
			{
				return this._GasStationTypeName;
			}
			set
			{
				if ((this._GasStationTypeName != value))
				{
					this._GasStationTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkingPressureName", DbType="VarChar(50)")]
		public string WorkingPressureName
		{
			get
			{
				return this._WorkingPressureName;
			}
			set
			{
				if ((this._WorkingPressureName != value))
				{
					this._WorkingPressureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseTypeName", DbType="VarChar(50)")]
		public string UseTypeName
		{
			get
			{
				return this._UseTypeName;
			}
			set
			{
				if ((this._UseTypeName != value))
				{
					this._UseTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineName", DbType="VarChar(50)")]
		public string LineName
		{
			get
			{
				return this._LineName;
			}
			set
			{
				if ((this._LineName != value))
				{
					this._LineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationLinkTypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StationLinkTypeName
		{
			get
			{
				return this._StationLinkTypeName;
			}
			set
			{
				if ((this._StationLinkTypeName != value))
				{
					this._StationLinkTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierAddress", DbType="VarChar(500)")]
		public string SupplierAddress
		{
			get
			{
				return this._SupplierAddress;
			}
			set
			{
				if ((this._SupplierAddress != value))
				{
					this._SupplierAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierTel", DbType="VarChar(50)")]
		public string SupplierTel
		{
			get
			{
				return this._SupplierTel;
			}
			set
			{
				if ((this._SupplierTel != value))
				{
					this._SupplierTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParametersName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ParametersName
		{
			get
			{
				return this._ParametersName;
			}
			set
			{
				if ((this._ParametersName != value))
				{
					this._ParametersName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_StationMonitoringStateParameters")]
	public partial class TBL_StationMonitoringStateParameter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _StationMonitoringState_Id;
		
		private int _Parameters_Id;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStationMonitoringState_IdChanging(int value);
    partial void OnStationMonitoringState_IdChanged();
    partial void OnParameters_IdChanging(int value);
    partial void OnParameters_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_StationMonitoringStateParameter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationMonitoringState_Id", DbType="Int NOT NULL")]
		public int StationMonitoringState_Id
		{
			get
			{
				return this._StationMonitoringState_Id;
			}
			set
			{
				if ((this._StationMonitoringState_Id != value))
				{
					this.OnStationMonitoringState_IdChanging(value);
					this.SendPropertyChanging();
					this._StationMonitoringState_Id = value;
					this.SendPropertyChanged("StationMonitoringState_Id");
					this.OnStationMonitoringState_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parameters_Id", DbType="Int NOT NULL")]
		public int Parameters_Id
		{
			get
			{
				return this._Parameters_Id;
			}
			set
			{
				if ((this._Parameters_Id != value))
				{
					this.OnParameters_IdChanging(value);
					this.SendPropertyChanging();
					this._Parameters_Id = value;
					this.SendPropertyChanged("Parameters_Id");
					this.OnParameters_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
