#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationManagement.Model.PressGageSupply
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GasStationManagement")]
	public partial class DataClassesPressGageSupplyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_PressGageSupply(TBL_PressGageSupply instance);
    partial void UpdateTBL_PressGageSupply(TBL_PressGageSupply instance);
    partial void DeleteTBL_PressGageSupply(TBL_PressGageSupply instance);
    #endregion
		
		public DataClassesPressGageSupplyDataContext() : 
				base(global::GasStationManagement.Model.Properties.Settings.Default.GasStationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPressGageSupplyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPressGageSupplyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPressGageSupplyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPressGageSupplyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_PressGageSupply> TBL_PressGageSupplies
		{
			get
			{
				return this.GetTable<TBL_PressGageSupply>();
			}
		}
		
		public System.Data.Linq.Table<VW_PressGageSupply> VW_PressGageSupplies
		{
			get
			{
				return this.GetTable<VW_PressGageSupply>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PressGageSupplyDelete")]
		public int SP_PressGageSupplyDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PressGage_Id", DbType="Int")] System.Nullable<int> pressGage_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PressGageSerialNo", DbType="VarChar(20)")] string pressGageSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pressGage_Id, pressGageSerialNo, msgRet);
			msgRet = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PressGageSupplyInsert")]
		public int SP_PressGageSupplyInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PressGage_Id", DbType="Int")] System.Nullable<int> pressGage_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PressGageSerialNo", DbType="VarChar(20)")] string pressGageSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplyDate", DbType="VarChar(10)")] string supplyDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="BigInt")] System.Nullable<long> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pressGage_Id, pressGageSerialNo, supplyDate, price, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PressGageSupplyUpdate")]
		public int SP_PressGageSupplyUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PressGage_Id", DbType="Int")] System.Nullable<int> pressGage_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PressGageSerialNo", DbType="VarChar(20)")] string pressGageSerialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplyDate", DbType="VarChar(10)")] string supplyDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="BigInt")] System.Nullable<long> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pressGage_Id, pressGageSerialNo, supplyDate, price, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PressGageSupply")]
	public partial class TBL_PressGageSupply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PressGage_Id;
		
		private string _PressGageSerialNo;
		
		private string _SupplyDate;
		
		private System.Nullable<long> _Price;
		
		private short _Suppliers_Id;
		
		private string _Description;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPressGage_IdChanging(int value);
    partial void OnPressGage_IdChanged();
    partial void OnPressGageSerialNoChanging(string value);
    partial void OnPressGageSerialNoChanged();
    partial void OnSupplyDateChanging(string value);
    partial void OnSupplyDateChanged();
    partial void OnPriceChanging(System.Nullable<long> value);
    partial void OnPriceChanged();
    partial void OnSuppliers_IdChanging(short value);
    partial void OnSuppliers_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public TBL_PressGageSupply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PressGage_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PressGage_Id
		{
			get
			{
				return this._PressGage_Id;
			}
			set
			{
				if ((this._PressGage_Id != value))
				{
					this.OnPressGage_IdChanging(value);
					this.SendPropertyChanging();
					this._PressGage_Id = value;
					this.SendPropertyChanged("PressGage_Id");
					this.OnPressGage_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PressGageSerialNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PressGageSerialNo
		{
			get
			{
				return this._PressGageSerialNo;
			}
			set
			{
				if ((this._PressGageSerialNo != value))
				{
					this.OnPressGageSerialNoChanging(value);
					this.SendPropertyChanging();
					this._PressGageSerialNo = value;
					this.SendPropertyChanged("PressGageSerialNo");
					this.OnPressGageSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SupplyDate
		{
			get
			{
				return this._SupplyDate;
			}
			set
			{
				if ((this._SupplyDate != value))
				{
					this.OnSupplyDateChanging(value);
					this.SendPropertyChanging();
					this._SupplyDate = value;
					this.SendPropertyChanged("SupplyDate");
					this.OnSupplyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this.OnSuppliers_IdChanging(value);
					this.SendPropertyChanging();
					this._Suppliers_Id = value;
					this.SendPropertyChanged("Suppliers_Id");
					this.OnSuppliers_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_PressGageSupply")]
	public partial class VW_PressGageSupply
	{
		
		private int _PressGage_Id;
		
		private string _PressGageSerialNo;
		
		private string _SupplyDate;
		
		private System.Nullable<long> _Price;
		
		private short _Suppliers_Id;
		
		private string _Description;
		
		private bool _IsActive;
		
		private string _Name;
		
		private string _Address;
		
		private string _Tel;
		
		private string _Brand;
		
		private double _GageSize;
		
		private int _PMax;
		
		private int _CalibrationDuration;
		
		public VW_PressGageSupply()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PressGage_Id", DbType="Int NOT NULL")]
		public int PressGage_Id
		{
			get
			{
				return this._PressGage_Id;
			}
			set
			{
				if ((this._PressGage_Id != value))
				{
					this._PressGage_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PressGageSerialNo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PressGageSerialNo
		{
			get
			{
				return this._PressGageSerialNo;
			}
			set
			{
				if ((this._PressGageSerialNo != value))
				{
					this._PressGageSerialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SupplyDate
		{
			get
			{
				return this._SupplyDate;
			}
			set
			{
				if ((this._SupplyDate != value))
				{
					this._SupplyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this._Suppliers_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this._Brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GageSize", DbType="Float NOT NULL")]
		public double GageSize
		{
			get
			{
				return this._GageSize;
			}
			set
			{
				if ((this._GageSize != value))
				{
					this._GageSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMax", DbType="Int NOT NULL")]
		public int PMax
		{
			get
			{
				return this._PMax;
			}
			set
			{
				if ((this._PMax != value))
				{
					this._PMax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalibrationDuration", DbType="Int NOT NULL")]
		public int CalibrationDuration
		{
			get
			{
				return this._CalibrationDuration;
			}
			set
			{
				if ((this._CalibrationDuration != value))
				{
					this._CalibrationDuration = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
