<?xml version="1.0" encoding="utf-8"?><Database Name="GasStationManagement" Class="DataClassesStationMonitoringStateDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=GasStationManagement;Integrated Security=True" SettingsObjectName="GasStationManagement.Model.Properties.Settings" SettingsPropertyName="GasStationManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_StationMonitoringState" Member="TBL_StationMonitoringStates">
    <Type Name="TBL_StationMonitoringState">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GasStation_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationLinkType_Id" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MonitoringSysState_Id" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MonitoringSysExeDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Suppliers_Id" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ChangeStateDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_StationMonitoringState" Member="VW_StationMonitoringStates">
    <Type Name="VW_StationMonitoringState">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GasStation_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationLinkType_Id" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MonitoringSysState_Id" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MonitoringSysExeDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Suppliers_Id" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ChangeStateDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GasStationCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GasStationName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GasStationBuildingDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleRegInfoStr" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ScheduleRegInfo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleSpecPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RanFew" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Heater_Few" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GasStationTypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkingPressureName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UseTypeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LineName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StationLinkTypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierAddress" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SupplierTel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MonitoringSysStateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SP_StationMonitoringStateDelete" Method="SP_StationMonitoringStateDelete">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(2000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_StationMonitoringStateInsert" Method="SP_StationMonitoringStateInsert">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="GasStation_Id" Parameter="gasStation_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="StationLinkType_Id" Parameter="stationLinkType_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="MonitoringSysState_Id" Parameter="monitoringSysState_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="MonitoringSysExeDate" Parameter="monitoringSysExeDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Suppliers_Id" Parameter="suppliers_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="ChangeStateDate" Parameter="changeStateDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_StationMonitoringStateUpdate" Method="SP_StationMonitoringStateUpdate">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="GasStation_Id" Parameter="gasStation_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="StationLinkType_Id" Parameter="stationLinkType_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="MonitoringSysState_Id" Parameter="monitoringSysState_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="MonitoringSysExeDate" Parameter="monitoringSysExeDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Suppliers_Id" Parameter="suppliers_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="ChangeStateDate" Parameter="changeStateDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>