#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationManagement.Model.StationMonitoringState
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GasStationManagement")]
	public partial class DataClassesStationMonitoringStateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_StationMonitoringState(TBL_StationMonitoringState instance);
    partial void UpdateTBL_StationMonitoringState(TBL_StationMonitoringState instance);
    partial void DeleteTBL_StationMonitoringState(TBL_StationMonitoringState instance);
    #endregion
		
		public DataClassesStationMonitoringStateDataContext() : 
				base(global::GasStationManagement.Model.Properties.Settings.Default.GasStationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesStationMonitoringStateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_StationMonitoringState> TBL_StationMonitoringStates
		{
			get
			{
				return this.GetTable<TBL_StationMonitoringState>();
			}
		}
		
		public System.Data.Linq.Table<VW_StationMonitoringState> VW_StationMonitoringStates
		{
			get
			{
				return this.GetTable<VW_StationMonitoringState>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_StationMonitoringStateDelete")]
		public int SP_StationMonitoringStateDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_StationMonitoringStateInsert")]
		public int SP_StationMonitoringStateInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStation_Id", DbType="Int")] System.Nullable<int> gasStation_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StationLinkType_Id", DbType="SmallInt")] System.Nullable<short> stationLinkType_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysState_Id", DbType="SmallInt")] System.Nullable<short> monitoringSysState_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysExeDate", DbType="VarChar(10)")] string monitoringSysExeDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeStateDate", DbType="VarChar(10)")] string changeStateDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, gasStation_Id, stationLinkType_Id, monitoringSysState_Id, monitoringSysExeDate, suppliers_Id, changeStateDate, description, isActive, msgRet);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_StationMonitoringStateUpdate")]
		public int SP_StationMonitoringStateUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStation_Id", DbType="Int")] System.Nullable<int> gasStation_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StationLinkType_Id", DbType="SmallInt")] System.Nullable<short> stationLinkType_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysState_Id", DbType="SmallInt")] System.Nullable<short> monitoringSysState_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysExeDate", DbType="VarChar(10)")] string monitoringSysExeDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeStateDate", DbType="VarChar(10)")] string changeStateDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, gasStation_Id, stationLinkType_Id, monitoringSysState_Id, monitoringSysExeDate, suppliers_Id, changeStateDate, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_StationMonitoringState")]
	public partial class TBL_StationMonitoringState : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _GasStation_Id;
		
		private System.Nullable<short> _StationLinkType_Id;
		
		private short _MonitoringSysState_Id;
		
		private string _MonitoringSysExeDate;
		
		private short _Suppliers_Id;
		
		private string _ChangeStateDate;
		
		private string _Description;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGasStation_IdChanging(int value);
    partial void OnGasStation_IdChanged();
    partial void OnStationLinkType_IdChanging(System.Nullable<short> value);
    partial void OnStationLinkType_IdChanged();
    partial void OnMonitoringSysState_IdChanging(short value);
    partial void OnMonitoringSysState_IdChanged();
    partial void OnMonitoringSysExeDateChanging(string value);
    partial void OnMonitoringSysExeDateChanged();
    partial void OnSuppliers_IdChanging(short value);
    partial void OnSuppliers_IdChanged();
    partial void OnChangeStateDateChanging(string value);
    partial void OnChangeStateDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public TBL_StationMonitoringState()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStation_Id", DbType="Int NOT NULL")]
		public int GasStation_Id
		{
			get
			{
				return this._GasStation_Id;
			}
			set
			{
				if ((this._GasStation_Id != value))
				{
					this.OnGasStation_IdChanging(value);
					this.SendPropertyChanging();
					this._GasStation_Id = value;
					this.SendPropertyChanged("GasStation_Id");
					this.OnGasStation_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationLinkType_Id", DbType="SmallInt")]
		public System.Nullable<short> StationLinkType_Id
		{
			get
			{
				return this._StationLinkType_Id;
			}
			set
			{
				if ((this._StationLinkType_Id != value))
				{
					this.OnStationLinkType_IdChanging(value);
					this.SendPropertyChanging();
					this._StationLinkType_Id = value;
					this.SendPropertyChanged("StationLinkType_Id");
					this.OnStationLinkType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysState_Id", DbType="SmallInt NOT NULL")]
		public short MonitoringSysState_Id
		{
			get
			{
				return this._MonitoringSysState_Id;
			}
			set
			{
				if ((this._MonitoringSysState_Id != value))
				{
					this.OnMonitoringSysState_IdChanging(value);
					this.SendPropertyChanging();
					this._MonitoringSysState_Id = value;
					this.SendPropertyChanged("MonitoringSysState_Id");
					this.OnMonitoringSysState_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysExeDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MonitoringSysExeDate
		{
			get
			{
				return this._MonitoringSysExeDate;
			}
			set
			{
				if ((this._MonitoringSysExeDate != value))
				{
					this.OnMonitoringSysExeDateChanging(value);
					this.SendPropertyChanging();
					this._MonitoringSysExeDate = value;
					this.SendPropertyChanged("MonitoringSysExeDate");
					this.OnMonitoringSysExeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this.OnSuppliers_IdChanging(value);
					this.SendPropertyChanging();
					this._Suppliers_Id = value;
					this.SendPropertyChanged("Suppliers_Id");
					this.OnSuppliers_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStateDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ChangeStateDate
		{
			get
			{
				return this._ChangeStateDate;
			}
			set
			{
				if ((this._ChangeStateDate != value))
				{
					this.OnChangeStateDateChanging(value);
					this.SendPropertyChanging();
					this._ChangeStateDate = value;
					this.SendPropertyChanged("ChangeStateDate");
					this.OnChangeStateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_StationMonitoringState")]
	public partial class VW_StationMonitoringState
	{
		
		private int _Id;
		
		private int _GasStation_Id;
		
		private System.Nullable<short> _StationLinkType_Id;
		
		private short _MonitoringSysState_Id;
		
		private string _MonitoringSysExeDate;
		
		private short _Suppliers_Id;
		
		private string _ChangeStateDate;
		
		private string _Description;
		
		private bool _IsActive;
		
		private string _GasStationCode;
		
		private string _GasStationName;
		
		private string _GasStationBuildingDate;
		
		private int _Capacity;
		
		private string _ScheduleRegInfoStr;
		
		private short _ScheduleRegInfo;
		
		private System.Nullable<int> _ScheduleSpecPeriod;
		
		private int _RanFew;
		
		private System.Nullable<int> _Heater_Few;
		
		private string _GasStationTypeName;
		
		private string _WorkingPressureName;
		
		private string _UseTypeName;
		
		private string _LineName;
		
		private string _StationLinkTypeName;
		
		private string _SupplierName;
		
		private string _SupplierAddress;
		
		private string _SupplierTel;
		
		private string _MonitoringSysStateName;
		
		public VW_StationMonitoringState()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStation_Id", DbType="Int NOT NULL")]
		public int GasStation_Id
		{
			get
			{
				return this._GasStation_Id;
			}
			set
			{
				if ((this._GasStation_Id != value))
				{
					this._GasStation_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationLinkType_Id", DbType="SmallInt")]
		public System.Nullable<short> StationLinkType_Id
		{
			get
			{
				return this._StationLinkType_Id;
			}
			set
			{
				if ((this._StationLinkType_Id != value))
				{
					this._StationLinkType_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysState_Id", DbType="SmallInt NOT NULL")]
		public short MonitoringSysState_Id
		{
			get
			{
				return this._MonitoringSysState_Id;
			}
			set
			{
				if ((this._MonitoringSysState_Id != value))
				{
					this._MonitoringSysState_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysExeDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MonitoringSysExeDate
		{
			get
			{
				return this._MonitoringSysExeDate;
			}
			set
			{
				if ((this._MonitoringSysExeDate != value))
				{
					this._MonitoringSysExeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt NOT NULL")]
		public short Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this._Suppliers_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStateDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ChangeStateDate
		{
			get
			{
				return this._ChangeStateDate;
			}
			set
			{
				if ((this._ChangeStateDate != value))
				{
					this._ChangeStateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GasStationCode
		{
			get
			{
				return this._GasStationCode;
			}
			set
			{
				if ((this._GasStationCode != value))
				{
					this._GasStationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GasStationName
		{
			get
			{
				return this._GasStationName;
			}
			set
			{
				if ((this._GasStationName != value))
				{
					this._GasStationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationBuildingDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GasStationBuildingDate
		{
			get
			{
				return this._GasStationBuildingDate;
			}
			set
			{
				if ((this._GasStationBuildingDate != value))
				{
					this._GasStationBuildingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Int NOT NULL")]
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this._Capacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleRegInfoStr", DbType="VarChar(8)")]
		public string ScheduleRegInfoStr
		{
			get
			{
				return this._ScheduleRegInfoStr;
			}
			set
			{
				if ((this._ScheduleRegInfoStr != value))
				{
					this._ScheduleRegInfoStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleRegInfo", DbType="SmallInt NOT NULL")]
		public short ScheduleRegInfo
		{
			get
			{
				return this._ScheduleRegInfo;
			}
			set
			{
				if ((this._ScheduleRegInfo != value))
				{
					this._ScheduleRegInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleSpecPeriod", DbType="Int")]
		public System.Nullable<int> ScheduleSpecPeriod
		{
			get
			{
				return this._ScheduleSpecPeriod;
			}
			set
			{
				if ((this._ScheduleSpecPeriod != value))
				{
					this._ScheduleSpecPeriod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanFew", DbType="Int NOT NULL")]
		public int RanFew
		{
			get
			{
				return this._RanFew;
			}
			set
			{
				if ((this._RanFew != value))
				{
					this._RanFew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heater_Few", DbType="Int")]
		public System.Nullable<int> Heater_Few
		{
			get
			{
				return this._Heater_Few;
			}
			set
			{
				if ((this._Heater_Few != value))
				{
					this._Heater_Few = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationTypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GasStationTypeName
		{
			get
			{
				return this._GasStationTypeName;
			}
			set
			{
				if ((this._GasStationTypeName != value))
				{
					this._GasStationTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkingPressureName", DbType="VarChar(50)")]
		public string WorkingPressureName
		{
			get
			{
				return this._WorkingPressureName;
			}
			set
			{
				if ((this._WorkingPressureName != value))
				{
					this._WorkingPressureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseTypeName", DbType="VarChar(50)")]
		public string UseTypeName
		{
			get
			{
				return this._UseTypeName;
			}
			set
			{
				if ((this._UseTypeName != value))
				{
					this._UseTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineName", DbType="VarChar(50)")]
		public string LineName
		{
			get
			{
				return this._LineName;
			}
			set
			{
				if ((this._LineName != value))
				{
					this._LineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationLinkTypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StationLinkTypeName
		{
			get
			{
				return this._StationLinkTypeName;
			}
			set
			{
				if ((this._StationLinkTypeName != value))
				{
					this._StationLinkTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierAddress", DbType="VarChar(500)")]
		public string SupplierAddress
		{
			get
			{
				return this._SupplierAddress;
			}
			set
			{
				if ((this._SupplierAddress != value))
				{
					this._SupplierAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierTel", DbType="VarChar(50)")]
		public string SupplierTel
		{
			get
			{
				return this._SupplierTel;
			}
			set
			{
				if ((this._SupplierTel != value))
				{
					this._SupplierTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysStateName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MonitoringSysStateName
		{
			get
			{
				return this._MonitoringSysStateName;
			}
			set
			{
				if ((this._MonitoringSysStateName != value))
				{
					this._MonitoringSysStateName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
