#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationManagement.Model.Table_TSample
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GasStationManagement")]
	public partial class DataClassesTable_TSampleDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_TSample(Table_TSample instance);
    partial void UpdateTable_TSample(Table_TSample instance);
    partial void DeleteTable_TSample(Table_TSample instance);
    #endregion
		
		public DataClassesTable_TSampleDataContext() : 
				base(global::GasStationManagement.Model.Properties.Settings.Default.GasStationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTable_TSampleDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTable_TSampleDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTable_TSampleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTable_TSampleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_Table_TSample> VW_Table_TSamples
		{
			get
			{
				return this.GetTable<VW_Table_TSample>();
			}
		}
		
		public System.Data.Linq.Table<Table_TSample> Table_TSamples
		{
			get
			{
				return this.GetTable<Table_TSample>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Table_TSampleClear")]
		public int SP_Table_TSampleClear([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), msgRet);
			msgRet = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Table_TInsertUpdate")]
		public int SP_Table_TInsertUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationCode", DbType="Char(3)")] string gasStationCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time_Stamp, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string strTimeStampShamsi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bInvalid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nProjectID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fSysUpTime_Hour, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nSourceID_OfResetPAC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bResetPAC_Pend, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fStationCapacity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fTotalQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fTotalQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInGasT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutGasT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInGasP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutGasP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fAirT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVb", DbType="BigInt")] System.Nullable<long> eK1_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVbD", DbType="BigInt")] System.Nullable<long> eK1_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVm", DbType="BigInt")] System.Nullable<long> eK1_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVmD", DbType="BigInt")] System.Nullable<long> eK1_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fP_Psi", DbType="Real")] System.Nullable<float> eK1_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fT", DbType="Real")] System.Nullable<float> eK1_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fC", DbType="Real")] System.Nullable<float> eK1_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fQm", DbType="Real")] System.Nullable<float> eK1_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fQb", DbType="Real")] System.Nullable<float> eK1_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fTbX", DbType="Real")] System.Nullable<float> eK1_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fPbX", DbType="Real")] System.Nullable<float> eK1_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nBatRemain", DbType="Int")] System.Nullable<int> eK1_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVb", DbType="BigInt")] System.Nullable<long> eK2_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVbD", DbType="BigInt")] System.Nullable<long> eK2_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVm", DbType="BigInt")] System.Nullable<long> eK2_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVmD", DbType="BigInt")] System.Nullable<long> eK2_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fP_Psi", DbType="Real")] System.Nullable<float> eK2_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fT", DbType="Real")] System.Nullable<float> eK2_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fC", DbType="Real")] System.Nullable<float> eK2_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fQm", DbType="Real")] System.Nullable<float> eK2_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fQb", DbType="Real")] System.Nullable<float> eK2_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fTbX", DbType="Real")] System.Nullable<float> eK2_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fPbX", DbType="Real")] System.Nullable<float> eK2_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nBatRemain", DbType="Int")] System.Nullable<int> eK2_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVb", DbType="BigInt")] System.Nullable<long> eK3_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVbD", DbType="BigInt")] System.Nullable<long> eK3_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVm", DbType="BigInt")] System.Nullable<long> eK3_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVmD", DbType="BigInt")] System.Nullable<long> eK3_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fP_Psi", DbType="Real")] System.Nullable<float> eK3_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fT", DbType="Real")] System.Nullable<float> eK3_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fC", DbType="Real")] System.Nullable<float> eK3_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fQm", DbType="Real")] System.Nullable<float> eK3_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fQb", DbType="Real")] System.Nullable<float> eK3_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fTbX", DbType="Real")] System.Nullable<float> eK3_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fPbX", DbType="Real")] System.Nullable<float> eK3_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nBatRemain", DbType="Int")] System.Nullable<int> eK3_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bWaterLLA_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fWaterT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bWaterLLA_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fWaterT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gasStationCode, time_Stamp, strTimeStampShamsi, bInvalid, nProjectID, fSysUpTime_Hour, nSourceID_OfResetPAC, bResetPAC_Pend, fStationCapacity, fTotalQb, fTotalQm, fInGasT, fOutGasT, fInGasP, fOutGasP, fAirT, eK1_nVb, eK1_nVbD, eK1_nVm, eK1_nVmD, eK1_fP_Psi, eK1_fT, eK1_fC, eK1_fQm, eK1_fQb, eK1_fTbX, eK1_fPbX, eK1_nBatRemain, eK2_nVb, eK2_nVbD, eK2_nVm, eK2_nVmD, eK2_fP_Psi, eK2_fT, eK2_fC, eK2_fQm, eK2_fQb, eK2_fTbX, eK2_fPbX, eK2_nBatRemain, eK3_nVb, eK3_nVbD, eK3_nVm, eK3_nVmD, eK3_fP_Psi, eK3_fT, eK3_fC, eK3_fQm, eK3_fQb, eK3_fTbX, eK3_fPbX, eK3_nBatRemain, fInT_Ht1, fOutT_Ht1, bWaterLLA_Ht1, fInT_Ht2, fOutT_Ht2, fWaterT_Ht2, bWaterLLA_Ht2, fWaterT_Ht1, msgRet);
			msgRet = ((string)(result.GetParameterValue(60)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Table_TSampleDelete")]
		public int SP_Table_TSampleDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Table_TSampleInsert")]
		public int SP_Table_TSampleInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationCode", DbType="VarChar(20)")] string gasStationCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationName", DbType="VarChar(100)")] string gasStationName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time_Stamp, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string strTimeStampShamsi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bInvalid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nStationID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nProjectID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fSysUpTime_Hour, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nSourceID_OfResetPAC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bResetPAC_Pend, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fStationCapacity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fTotalQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fTotalQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInGasT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutGasT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInGasP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutGasP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fAirT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVb", DbType="BigInt")] System.Nullable<long> eK1_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVbD", DbType="BigInt")] System.Nullable<long> eK1_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVm", DbType="BigInt")] System.Nullable<long> eK1_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVmD", DbType="BigInt")] System.Nullable<long> eK1_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fP_Psi", DbType="Real")] System.Nullable<float> eK1_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fT", DbType="Real")] System.Nullable<float> eK1_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fC", DbType="Real")] System.Nullable<float> eK1_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fQm", DbType="Real")] System.Nullable<float> eK1_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fQb", DbType="Real")] System.Nullable<float> eK1_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fTbX", DbType="Real")] System.Nullable<float> eK1_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fPbX", DbType="Real")] System.Nullable<float> eK1_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nBatRemain", DbType="Int")] System.Nullable<int> eK1_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVb", DbType="BigInt")] System.Nullable<long> eK2_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVbD", DbType="BigInt")] System.Nullable<long> eK2_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVm", DbType="BigInt")] System.Nullable<long> eK2_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVmD", DbType="BigInt")] System.Nullable<long> eK2_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fP_Psi", DbType="Real")] System.Nullable<float> eK2_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fT", DbType="Real")] System.Nullable<float> eK2_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fC", DbType="Real")] System.Nullable<float> eK2_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fQm", DbType="Real")] System.Nullable<float> eK2_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fQb", DbType="Real")] System.Nullable<float> eK2_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fTbX", DbType="Real")] System.Nullable<float> eK2_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fPbX", DbType="Real")] System.Nullable<float> eK2_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nBatRemain", DbType="Int")] System.Nullable<int> eK2_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVb", DbType="BigInt")] System.Nullable<long> eK3_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVbD", DbType="BigInt")] System.Nullable<long> eK3_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVm", DbType="BigInt")] System.Nullable<long> eK3_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVmD", DbType="BigInt")] System.Nullable<long> eK3_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fP_Psi", DbType="Real")] System.Nullable<float> eK3_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fT", DbType="Real")] System.Nullable<float> eK3_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fC", DbType="Real")] System.Nullable<float> eK3_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fQm", DbType="Real")] System.Nullable<float> eK3_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fQb", DbType="Real")] System.Nullable<float> eK3_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fTbX", DbType="Real")] System.Nullable<float> eK3_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fPbX", DbType="Real")] System.Nullable<float> eK3_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nBatRemain", DbType="Int")] System.Nullable<int> eK3_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bWaterLLA_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fWaterT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bWaterLLA_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fWaterT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, gasStationCode, gasStationName, time_Stamp, strTimeStampShamsi, bInvalid, nStationID, nProjectID, fSysUpTime_Hour, nSourceID_OfResetPAC, bResetPAC_Pend, fStationCapacity, fTotalQb, fTotalQm, fInGasT, fOutGasT, fInGasP, fOutGasP, fAirT, eK1_nVb, eK1_nVbD, eK1_nVm, eK1_nVmD, eK1_fP_Psi, eK1_fT, eK1_fC, eK1_fQm, eK1_fQb, eK1_fTbX, eK1_fPbX, eK1_nBatRemain, eK2_nVb, eK2_nVbD, eK2_nVm, eK2_nVmD, eK2_fP_Psi, eK2_fT, eK2_fC, eK2_fQm, eK2_fQb, eK2_fTbX, eK2_fPbX, eK2_nBatRemain, eK3_nVb, eK3_nVbD, eK3_nVm, eK3_nVmD, eK3_fP_Psi, eK3_fT, eK3_fC, eK3_fQm, eK3_fQb, eK3_fTbX, eK3_fPbX, eK3_nBatRemain, fInT_Ht1, fOutT_Ht1, bWaterLLA_Ht1, fInT_Ht2, fOutT_Ht2, fWaterT_Ht2, bWaterLLA_Ht2, fWaterT_Ht1, msgRet);
			msgRet = ((string)(result.GetParameterValue(63)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Table_TSampleUpdate")]
		public int SP_Table_TSampleUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationCode", DbType="VarChar(20)")] string gasStationCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationName", DbType="VarChar(100)")] string gasStationName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time_Stamp, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string strTimeStampShamsi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bInvalid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nStationID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nProjectID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fSysUpTime_Hour, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nSourceID_OfResetPAC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bResetPAC_Pend, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fStationCapacity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fTotalQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fTotalQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInGasT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutGasT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInGasP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutGasP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fAirT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVb", DbType="BigInt")] System.Nullable<long> eK1_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVbD", DbType="BigInt")] System.Nullable<long> eK1_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVm", DbType="BigInt")] System.Nullable<long> eK1_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nVmD", DbType="BigInt")] System.Nullable<long> eK1_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fP_Psi", DbType="Real")] System.Nullable<float> eK1_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fT", DbType="Real")] System.Nullable<float> eK1_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fC", DbType="Real")] System.Nullable<float> eK1_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fQm", DbType="Real")] System.Nullable<float> eK1_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fQb", DbType="Real")] System.Nullable<float> eK1_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fTbX", DbType="Real")] System.Nullable<float> eK1_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_fPbX", DbType="Real")] System.Nullable<float> eK1_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK1_nBatRemain", DbType="Int")] System.Nullable<int> eK1_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVb", DbType="BigInt")] System.Nullable<long> eK2_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVbD", DbType="BigInt")] System.Nullable<long> eK2_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVm", DbType="BigInt")] System.Nullable<long> eK2_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nVmD", DbType="BigInt")] System.Nullable<long> eK2_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fP_Psi", DbType="Real")] System.Nullable<float> eK2_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fT", DbType="Real")] System.Nullable<float> eK2_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fC", DbType="Real")] System.Nullable<float> eK2_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fQm", DbType="Real")] System.Nullable<float> eK2_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fQb", DbType="Real")] System.Nullable<float> eK2_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fTbX", DbType="Real")] System.Nullable<float> eK2_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_fPbX", DbType="Real")] System.Nullable<float> eK2_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK2_nBatRemain", DbType="Int")] System.Nullable<int> eK2_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVb", DbType="BigInt")] System.Nullable<long> eK3_nVb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVbD", DbType="BigInt")] System.Nullable<long> eK3_nVbD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVm", DbType="BigInt")] System.Nullable<long> eK3_nVm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nVmD", DbType="BigInt")] System.Nullable<long> eK3_nVmD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fP_Psi", DbType="Real")] System.Nullable<float> eK3_fP_Psi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fT", DbType="Real")] System.Nullable<float> eK3_fT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fC", DbType="Real")] System.Nullable<float> eK3_fC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fQm", DbType="Real")] System.Nullable<float> eK3_fQm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fQb", DbType="Real")] System.Nullable<float> eK3_fQb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fTbX", DbType="Real")] System.Nullable<float> eK3_fTbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_fPbX", DbType="Real")] System.Nullable<float> eK3_fPbX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EK3_nBatRemain", DbType="Int")] System.Nullable<int> eK3_nBatRemain, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bWaterLLA_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fInT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fOutT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fWaterT_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bWaterLLA_Ht2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> fWaterT_Ht1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, gasStationCode, gasStationName, time_Stamp, strTimeStampShamsi, bInvalid, nStationID, nProjectID, fSysUpTime_Hour, nSourceID_OfResetPAC, bResetPAC_Pend, fStationCapacity, fTotalQb, fTotalQm, fInGasT, fOutGasT, fInGasP, fOutGasP, fAirT, eK1_nVb, eK1_nVbD, eK1_nVm, eK1_nVmD, eK1_fP_Psi, eK1_fT, eK1_fC, eK1_fQm, eK1_fQb, eK1_fTbX, eK1_fPbX, eK1_nBatRemain, eK2_nVb, eK2_nVbD, eK2_nVm, eK2_nVmD, eK2_fP_Psi, eK2_fT, eK2_fC, eK2_fQm, eK2_fQb, eK2_fTbX, eK2_fPbX, eK2_nBatRemain, eK3_nVb, eK3_nVbD, eK3_nVm, eK3_nVmD, eK3_fP_Psi, eK3_fT, eK3_fC, eK3_fQm, eK3_fQb, eK3_fTbX, eK3_fPbX, eK3_nBatRemain, fInT_Ht1, fOutT_Ht1, bWaterLLA_Ht1, fInT_Ht2, fOutT_Ht2, fWaterT_Ht2, bWaterLLA_Ht2, fWaterT_Ht1, msgRet);
			msgRet = ((string)(result.GetParameterValue(63)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_Table_TSample")]
	public partial class VW_Table_TSample
	{
		
		private int _Id;
		
		private string _GasStationCode;
		
		private string _GasStationName;
		
		private System.Nullable<System.DateTime> _time_Stamp;
		
		private string _strTimeStampShamsi;
		
		private System.Nullable<bool> _bInvalid;
		
		private System.Nullable<int> _nStationID;
		
		private System.Nullable<int> _nProjectID;
		
		private System.Nullable<float> _fSysUpTime_Hour;
		
		private System.Nullable<int> _nSourceID_OfResetPAC;
		
		private System.Nullable<bool> _bResetPAC_Pend;
		
		private System.Nullable<float> _fStationCapacity;
		
		private System.Nullable<float> _fTotalQb;
		
		private System.Nullable<float> _fTotalQm;
		
		private System.Nullable<float> _fInGasT;
		
		private System.Nullable<float> _fOutGasT;
		
		private System.Nullable<float> _fInGasP;
		
		private System.Nullable<float> _fOutGasP;
		
		private System.Nullable<float> _fAirT;
		
		private System.Nullable<long> _EK1_nVb;
		
		private System.Nullable<long> _EK1_nVbD;
		
		private System.Nullable<long> _EK1_nVm;
		
		private System.Nullable<long> _EK1_nVmD;
		
		private System.Nullable<float> _EK1_fP_Psi;
		
		private System.Nullable<float> _EK1_fT;
		
		private System.Nullable<float> _EK1_fC;
		
		private System.Nullable<float> _EK1_fQm;
		
		private System.Nullable<float> _EK1_fQb;
		
		private System.Nullable<float> _EK1_fTbX;
		
		private System.Nullable<float> _EK1_fPbX;
		
		private System.Nullable<int> _EK1_nBatRemain;
		
		private System.Nullable<long> _EK2_nVb;
		
		private System.Nullable<long> _EK2_nVbD;
		
		private System.Nullable<long> _EK2_nVm;
		
		private System.Nullable<long> _EK2_nVmD;
		
		private System.Nullable<float> _EK2_fP_Psi;
		
		private System.Nullable<float> _EK2_fT;
		
		private System.Nullable<float> _EK2_fC;
		
		private System.Nullable<float> _EK2_fQm;
		
		private System.Nullable<float> _EK2_fQb;
		
		private System.Nullable<float> _EK2_fTbX;
		
		private System.Nullable<float> _EK2_fPbX;
		
		private System.Nullable<int> _EK2_nBatRemain;
		
		private System.Nullable<long> _EK3_nVb;
		
		private System.Nullable<long> _EK3_nVbD;
		
		private System.Nullable<long> _EK3_nVm;
		
		private System.Nullable<long> _EK3_nVmD;
		
		private System.Nullable<float> _EK3_fP_Psi;
		
		private System.Nullable<float> _EK3_fT;
		
		private System.Nullable<float> _EK3_fC;
		
		private System.Nullable<float> _EK3_fQm;
		
		private System.Nullable<float> _EK3_fQb;
		
		private System.Nullable<float> _EK3_fTbX;
		
		private System.Nullable<float> _EK3_fPbX;
		
		private System.Nullable<int> _EK3_nBatRemain;
		
		private System.Nullable<float> _fInT_Ht1;
		
		private System.Nullable<float> _fOutT_Ht1;
		
		private System.Nullable<bool> _bWaterLLA_Ht1;
		
		private System.Nullable<float> _fInT_Ht2;
		
		private System.Nullable<float> _fOutT_Ht2;
		
		private System.Nullable<float> _fWaterT_Ht2;
		
		private System.Nullable<bool> _bWaterLLA_Ht2;
		
		private System.Nullable<float> _fWaterT_Ht1;
		
		public VW_Table_TSample()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationCode", DbType="VarChar(20)")]
		public string GasStationCode
		{
			get
			{
				return this._GasStationCode;
			}
			set
			{
				if ((this._GasStationCode != value))
				{
					this._GasStationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationName", DbType="VarChar(100)")]
		public string GasStationName
		{
			get
			{
				return this._GasStationName;
			}
			set
			{
				if ((this._GasStationName != value))
				{
					this._GasStationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_Stamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> time_Stamp
		{
			get
			{
				return this._time_Stamp;
			}
			set
			{
				if ((this._time_Stamp != value))
				{
					this._time_Stamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTimeStampShamsi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string strTimeStampShamsi
		{
			get
			{
				return this._strTimeStampShamsi;
			}
			set
			{
				if ((this._strTimeStampShamsi != value))
				{
					this._strTimeStampShamsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bInvalid", DbType="Bit")]
		public System.Nullable<bool> bInvalid
		{
			get
			{
				return this._bInvalid;
			}
			set
			{
				if ((this._bInvalid != value))
				{
					this._bInvalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nStationID", DbType="Int")]
		public System.Nullable<int> nStationID
		{
			get
			{
				return this._nStationID;
			}
			set
			{
				if ((this._nStationID != value))
				{
					this._nStationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nProjectID", DbType="Int")]
		public System.Nullable<int> nProjectID
		{
			get
			{
				return this._nProjectID;
			}
			set
			{
				if ((this._nProjectID != value))
				{
					this._nProjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSysUpTime_Hour", DbType="Real")]
		public System.Nullable<float> fSysUpTime_Hour
		{
			get
			{
				return this._fSysUpTime_Hour;
			}
			set
			{
				if ((this._fSysUpTime_Hour != value))
				{
					this._fSysUpTime_Hour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nSourceID_OfResetPAC", DbType="Int")]
		public System.Nullable<int> nSourceID_OfResetPAC
		{
			get
			{
				return this._nSourceID_OfResetPAC;
			}
			set
			{
				if ((this._nSourceID_OfResetPAC != value))
				{
					this._nSourceID_OfResetPAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bResetPAC_Pend", DbType="Bit")]
		public System.Nullable<bool> bResetPAC_Pend
		{
			get
			{
				return this._bResetPAC_Pend;
			}
			set
			{
				if ((this._bResetPAC_Pend != value))
				{
					this._bResetPAC_Pend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fStationCapacity", DbType="Real")]
		public System.Nullable<float> fStationCapacity
		{
			get
			{
				return this._fStationCapacity;
			}
			set
			{
				if ((this._fStationCapacity != value))
				{
					this._fStationCapacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fTotalQb", DbType="Real")]
		public System.Nullable<float> fTotalQb
		{
			get
			{
				return this._fTotalQb;
			}
			set
			{
				if ((this._fTotalQb != value))
				{
					this._fTotalQb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fTotalQm", DbType="Real")]
		public System.Nullable<float> fTotalQm
		{
			get
			{
				return this._fTotalQm;
			}
			set
			{
				if ((this._fTotalQm != value))
				{
					this._fTotalQm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInGasT", DbType="Real")]
		public System.Nullable<float> fInGasT
		{
			get
			{
				return this._fInGasT;
			}
			set
			{
				if ((this._fInGasT != value))
				{
					this._fInGasT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutGasT", DbType="Real")]
		public System.Nullable<float> fOutGasT
		{
			get
			{
				return this._fOutGasT;
			}
			set
			{
				if ((this._fOutGasT != value))
				{
					this._fOutGasT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInGasP", DbType="Real")]
		public System.Nullable<float> fInGasP
		{
			get
			{
				return this._fInGasP;
			}
			set
			{
				if ((this._fInGasP != value))
				{
					this._fInGasP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutGasP", DbType="Real")]
		public System.Nullable<float> fOutGasP
		{
			get
			{
				return this._fOutGasP;
			}
			set
			{
				if ((this._fOutGasP != value))
				{
					this._fOutGasP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAirT", DbType="Real")]
		public System.Nullable<float> fAirT
		{
			get
			{
				return this._fAirT;
			}
			set
			{
				if ((this._fAirT != value))
				{
					this._fAirT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVb", DbType="BigInt")]
		public System.Nullable<long> EK1_nVb
		{
			get
			{
				return this._EK1_nVb;
			}
			set
			{
				if ((this._EK1_nVb != value))
				{
					this._EK1_nVb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVbD", DbType="BigInt")]
		public System.Nullable<long> EK1_nVbD
		{
			get
			{
				return this._EK1_nVbD;
			}
			set
			{
				if ((this._EK1_nVbD != value))
				{
					this._EK1_nVbD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVm", DbType="BigInt")]
		public System.Nullable<long> EK1_nVm
		{
			get
			{
				return this._EK1_nVm;
			}
			set
			{
				if ((this._EK1_nVm != value))
				{
					this._EK1_nVm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVmD", DbType="BigInt")]
		public System.Nullable<long> EK1_nVmD
		{
			get
			{
				return this._EK1_nVmD;
			}
			set
			{
				if ((this._EK1_nVmD != value))
				{
					this._EK1_nVmD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fP_Psi", DbType="Real")]
		public System.Nullable<float> EK1_fP_Psi
		{
			get
			{
				return this._EK1_fP_Psi;
			}
			set
			{
				if ((this._EK1_fP_Psi != value))
				{
					this._EK1_fP_Psi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fT", DbType="Real")]
		public System.Nullable<float> EK1_fT
		{
			get
			{
				return this._EK1_fT;
			}
			set
			{
				if ((this._EK1_fT != value))
				{
					this._EK1_fT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fC", DbType="Real")]
		public System.Nullable<float> EK1_fC
		{
			get
			{
				return this._EK1_fC;
			}
			set
			{
				if ((this._EK1_fC != value))
				{
					this._EK1_fC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fQm", DbType="Real")]
		public System.Nullable<float> EK1_fQm
		{
			get
			{
				return this._EK1_fQm;
			}
			set
			{
				if ((this._EK1_fQm != value))
				{
					this._EK1_fQm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fQb", DbType="Real")]
		public System.Nullable<float> EK1_fQb
		{
			get
			{
				return this._EK1_fQb;
			}
			set
			{
				if ((this._EK1_fQb != value))
				{
					this._EK1_fQb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fTbX", DbType="Real")]
		public System.Nullable<float> EK1_fTbX
		{
			get
			{
				return this._EK1_fTbX;
			}
			set
			{
				if ((this._EK1_fTbX != value))
				{
					this._EK1_fTbX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fPbX", DbType="Real")]
		public System.Nullable<float> EK1_fPbX
		{
			get
			{
				return this._EK1_fPbX;
			}
			set
			{
				if ((this._EK1_fPbX != value))
				{
					this._EK1_fPbX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nBatRemain", DbType="Int")]
		public System.Nullable<int> EK1_nBatRemain
		{
			get
			{
				return this._EK1_nBatRemain;
			}
			set
			{
				if ((this._EK1_nBatRemain != value))
				{
					this._EK1_nBatRemain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVb", DbType="BigInt")]
		public System.Nullable<long> EK2_nVb
		{
			get
			{
				return this._EK2_nVb;
			}
			set
			{
				if ((this._EK2_nVb != value))
				{
					this._EK2_nVb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVbD", DbType="BigInt")]
		public System.Nullable<long> EK2_nVbD
		{
			get
			{
				return this._EK2_nVbD;
			}
			set
			{
				if ((this._EK2_nVbD != value))
				{
					this._EK2_nVbD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVm", DbType="BigInt")]
		public System.Nullable<long> EK2_nVm
		{
			get
			{
				return this._EK2_nVm;
			}
			set
			{
				if ((this._EK2_nVm != value))
				{
					this._EK2_nVm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVmD", DbType="BigInt")]
		public System.Nullable<long> EK2_nVmD
		{
			get
			{
				return this._EK2_nVmD;
			}
			set
			{
				if ((this._EK2_nVmD != value))
				{
					this._EK2_nVmD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fP_Psi", DbType="Real")]
		public System.Nullable<float> EK2_fP_Psi
		{
			get
			{
				return this._EK2_fP_Psi;
			}
			set
			{
				if ((this._EK2_fP_Psi != value))
				{
					this._EK2_fP_Psi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fT", DbType="Real")]
		public System.Nullable<float> EK2_fT
		{
			get
			{
				return this._EK2_fT;
			}
			set
			{
				if ((this._EK2_fT != value))
				{
					this._EK2_fT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fC", DbType="Real")]
		public System.Nullable<float> EK2_fC
		{
			get
			{
				return this._EK2_fC;
			}
			set
			{
				if ((this._EK2_fC != value))
				{
					this._EK2_fC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fQm", DbType="Real")]
		public System.Nullable<float> EK2_fQm
		{
			get
			{
				return this._EK2_fQm;
			}
			set
			{
				if ((this._EK2_fQm != value))
				{
					this._EK2_fQm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fQb", DbType="Real")]
		public System.Nullable<float> EK2_fQb
		{
			get
			{
				return this._EK2_fQb;
			}
			set
			{
				if ((this._EK2_fQb != value))
				{
					this._EK2_fQb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fTbX", DbType="Real")]
		public System.Nullable<float> EK2_fTbX
		{
			get
			{
				return this._EK2_fTbX;
			}
			set
			{
				if ((this._EK2_fTbX != value))
				{
					this._EK2_fTbX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fPbX", DbType="Real")]
		public System.Nullable<float> EK2_fPbX
		{
			get
			{
				return this._EK2_fPbX;
			}
			set
			{
				if ((this._EK2_fPbX != value))
				{
					this._EK2_fPbX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nBatRemain", DbType="Int")]
		public System.Nullable<int> EK2_nBatRemain
		{
			get
			{
				return this._EK2_nBatRemain;
			}
			set
			{
				if ((this._EK2_nBatRemain != value))
				{
					this._EK2_nBatRemain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVb", DbType="BigInt")]
		public System.Nullable<long> EK3_nVb
		{
			get
			{
				return this._EK3_nVb;
			}
			set
			{
				if ((this._EK3_nVb != value))
				{
					this._EK3_nVb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVbD", DbType="BigInt")]
		public System.Nullable<long> EK3_nVbD
		{
			get
			{
				return this._EK3_nVbD;
			}
			set
			{
				if ((this._EK3_nVbD != value))
				{
					this._EK3_nVbD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVm", DbType="BigInt")]
		public System.Nullable<long> EK3_nVm
		{
			get
			{
				return this._EK3_nVm;
			}
			set
			{
				if ((this._EK3_nVm != value))
				{
					this._EK3_nVm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVmD", DbType="BigInt")]
		public System.Nullable<long> EK3_nVmD
		{
			get
			{
				return this._EK3_nVmD;
			}
			set
			{
				if ((this._EK3_nVmD != value))
				{
					this._EK3_nVmD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fP_Psi", DbType="Real")]
		public System.Nullable<float> EK3_fP_Psi
		{
			get
			{
				return this._EK3_fP_Psi;
			}
			set
			{
				if ((this._EK3_fP_Psi != value))
				{
					this._EK3_fP_Psi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fT", DbType="Real")]
		public System.Nullable<float> EK3_fT
		{
			get
			{
				return this._EK3_fT;
			}
			set
			{
				if ((this._EK3_fT != value))
				{
					this._EK3_fT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fC", DbType="Real")]
		public System.Nullable<float> EK3_fC
		{
			get
			{
				return this._EK3_fC;
			}
			set
			{
				if ((this._EK3_fC != value))
				{
					this._EK3_fC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fQm", DbType="Real")]
		public System.Nullable<float> EK3_fQm
		{
			get
			{
				return this._EK3_fQm;
			}
			set
			{
				if ((this._EK3_fQm != value))
				{
					this._EK3_fQm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fQb", DbType="Real")]
		public System.Nullable<float> EK3_fQb
		{
			get
			{
				return this._EK3_fQb;
			}
			set
			{
				if ((this._EK3_fQb != value))
				{
					this._EK3_fQb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fTbX", DbType="Real")]
		public System.Nullable<float> EK3_fTbX
		{
			get
			{
				return this._EK3_fTbX;
			}
			set
			{
				if ((this._EK3_fTbX != value))
				{
					this._EK3_fTbX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fPbX", DbType="Real")]
		public System.Nullable<float> EK3_fPbX
		{
			get
			{
				return this._EK3_fPbX;
			}
			set
			{
				if ((this._EK3_fPbX != value))
				{
					this._EK3_fPbX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nBatRemain", DbType="Int")]
		public System.Nullable<int> EK3_nBatRemain
		{
			get
			{
				return this._EK3_nBatRemain;
			}
			set
			{
				if ((this._EK3_nBatRemain != value))
				{
					this._EK3_nBatRemain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInT_Ht1", DbType="Real")]
		public System.Nullable<float> fInT_Ht1
		{
			get
			{
				return this._fInT_Ht1;
			}
			set
			{
				if ((this._fInT_Ht1 != value))
				{
					this._fInT_Ht1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutT_Ht1", DbType="Real")]
		public System.Nullable<float> fOutT_Ht1
		{
			get
			{
				return this._fOutT_Ht1;
			}
			set
			{
				if ((this._fOutT_Ht1 != value))
				{
					this._fOutT_Ht1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bWaterLLA_Ht1", DbType="Bit")]
		public System.Nullable<bool> bWaterLLA_Ht1
		{
			get
			{
				return this._bWaterLLA_Ht1;
			}
			set
			{
				if ((this._bWaterLLA_Ht1 != value))
				{
					this._bWaterLLA_Ht1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInT_Ht2", DbType="Real")]
		public System.Nullable<float> fInT_Ht2
		{
			get
			{
				return this._fInT_Ht2;
			}
			set
			{
				if ((this._fInT_Ht2 != value))
				{
					this._fInT_Ht2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutT_Ht2", DbType="Real")]
		public System.Nullable<float> fOutT_Ht2
		{
			get
			{
				return this._fOutT_Ht2;
			}
			set
			{
				if ((this._fOutT_Ht2 != value))
				{
					this._fOutT_Ht2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fWaterT_Ht2", DbType="Real")]
		public System.Nullable<float> fWaterT_Ht2
		{
			get
			{
				return this._fWaterT_Ht2;
			}
			set
			{
				if ((this._fWaterT_Ht2 != value))
				{
					this._fWaterT_Ht2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bWaterLLA_Ht2", DbType="Bit")]
		public System.Nullable<bool> bWaterLLA_Ht2
		{
			get
			{
				return this._bWaterLLA_Ht2;
			}
			set
			{
				if ((this._bWaterLLA_Ht2 != value))
				{
					this._bWaterLLA_Ht2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fWaterT_Ht1", DbType="Real")]
		public System.Nullable<float> fWaterT_Ht1
		{
			get
			{
				return this._fWaterT_Ht1;
			}
			set
			{
				if ((this._fWaterT_Ht1 != value))
				{
					this._fWaterT_Ht1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_TSample")]
	public partial class Table_TSample : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GasStationCode;
		
		private string _GasStationName;
		
		private System.Nullable<System.DateTime> _time_Stamp;
		
		private string _strTimeStampShamsi;
		
		private System.Nullable<bool> _bInvalid;
		
		private System.Nullable<int> _nStationID;
		
		private System.Nullable<int> _nProjectID;
		
		private System.Nullable<float> _fSysUpTime_Hour;
		
		private System.Nullable<int> _nSourceID_OfResetPAC;
		
		private System.Nullable<bool> _bResetPAC_Pend;
		
		private System.Nullable<float> _fStationCapacity;
		
		private System.Nullable<float> _fTotalQb;
		
		private System.Nullable<float> _fTotalQm;
		
		private System.Nullable<float> _fInGasT;
		
		private System.Nullable<float> _fOutGasT;
		
		private System.Nullable<float> _fInGasP;
		
		private System.Nullable<float> _fOutGasP;
		
		private System.Nullable<float> _fAirT;
		
		private System.Nullable<long> _EK1_nVb;
		
		private System.Nullable<long> _EK1_nVbD;
		
		private System.Nullable<long> _EK1_nVm;
		
		private System.Nullable<long> _EK1_nVmD;
		
		private System.Nullable<float> _EK1_fP_Psi;
		
		private System.Nullable<float> _EK1_fT;
		
		private System.Nullable<float> _EK1_fC;
		
		private System.Nullable<float> _EK1_fQm;
		
		private System.Nullable<float> _EK1_fQb;
		
		private System.Nullable<float> _EK1_fTbX;
		
		private System.Nullable<float> _EK1_fPbX;
		
		private System.Nullable<int> _EK1_nBatRemain;
		
		private System.Nullable<long> _EK2_nVb;
		
		private System.Nullable<long> _EK2_nVbD;
		
		private System.Nullable<long> _EK2_nVm;
		
		private System.Nullable<long> _EK2_nVmD;
		
		private System.Nullable<float> _EK2_fP_Psi;
		
		private System.Nullable<float> _EK2_fT;
		
		private System.Nullable<float> _EK2_fC;
		
		private System.Nullable<float> _EK2_fQm;
		
		private System.Nullable<float> _EK2_fQb;
		
		private System.Nullable<float> _EK2_fTbX;
		
		private System.Nullable<float> _EK2_fPbX;
		
		private System.Nullable<int> _EK2_nBatRemain;
		
		private System.Nullable<long> _EK3_nVb;
		
		private System.Nullable<long> _EK3_nVbD;
		
		private System.Nullable<long> _EK3_nVm;
		
		private System.Nullable<long> _EK3_nVmD;
		
		private System.Nullable<float> _EK3_fP_Psi;
		
		private System.Nullable<float> _EK3_fT;
		
		private System.Nullable<float> _EK3_fC;
		
		private System.Nullable<float> _EK3_fQm;
		
		private System.Nullable<float> _EK3_fQb;
		
		private System.Nullable<float> _EK3_fTbX;
		
		private System.Nullable<float> _EK3_fPbX;
		
		private System.Nullable<int> _EK3_nBatRemain;
		
		private System.Nullable<float> _fInT_Ht1;
		
		private System.Nullable<float> _fOutT_Ht1;
		
		private System.Nullable<bool> _bWaterLLA_Ht1;
		
		private System.Nullable<float> _fInT_Ht2;
		
		private System.Nullable<float> _fOutT_Ht2;
		
		private System.Nullable<float> _fWaterT_Ht2;
		
		private System.Nullable<bool> _bWaterLLA_Ht2;
		
		private System.Nullable<float> _fWaterT_Ht1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGasStationCodeChanging(string value);
    partial void OnGasStationCodeChanged();
    partial void OnGasStationNameChanging(string value);
    partial void OnGasStationNameChanged();
    partial void Ontime_StampChanging(System.Nullable<System.DateTime> value);
    partial void Ontime_StampChanged();
    partial void OnstrTimeStampShamsiChanging(string value);
    partial void OnstrTimeStampShamsiChanged();
    partial void OnbInvalidChanging(System.Nullable<bool> value);
    partial void OnbInvalidChanged();
    partial void OnnStationIDChanging(System.Nullable<int> value);
    partial void OnnStationIDChanged();
    partial void OnnProjectIDChanging(System.Nullable<int> value);
    partial void OnnProjectIDChanged();
    partial void OnfSysUpTime_HourChanging(System.Nullable<float> value);
    partial void OnfSysUpTime_HourChanged();
    partial void OnnSourceID_OfResetPACChanging(System.Nullable<int> value);
    partial void OnnSourceID_OfResetPACChanged();
    partial void OnbResetPAC_PendChanging(System.Nullable<bool> value);
    partial void OnbResetPAC_PendChanged();
    partial void OnfStationCapacityChanging(System.Nullable<float> value);
    partial void OnfStationCapacityChanged();
    partial void OnfTotalQbChanging(System.Nullable<float> value);
    partial void OnfTotalQbChanged();
    partial void OnfTotalQmChanging(System.Nullable<float> value);
    partial void OnfTotalQmChanged();
    partial void OnfInGasTChanging(System.Nullable<float> value);
    partial void OnfInGasTChanged();
    partial void OnfOutGasTChanging(System.Nullable<float> value);
    partial void OnfOutGasTChanged();
    partial void OnfInGasPChanging(System.Nullable<float> value);
    partial void OnfInGasPChanged();
    partial void OnfOutGasPChanging(System.Nullable<float> value);
    partial void OnfOutGasPChanged();
    partial void OnfAirTChanging(System.Nullable<float> value);
    partial void OnfAirTChanged();
    partial void OnEK1_nVbChanging(System.Nullable<long> value);
    partial void OnEK1_nVbChanged();
    partial void OnEK1_nVbDChanging(System.Nullable<long> value);
    partial void OnEK1_nVbDChanged();
    partial void OnEK1_nVmChanging(System.Nullable<long> value);
    partial void OnEK1_nVmChanged();
    partial void OnEK1_nVmDChanging(System.Nullable<long> value);
    partial void OnEK1_nVmDChanged();
    partial void OnEK1_fP_PsiChanging(System.Nullable<float> value);
    partial void OnEK1_fP_PsiChanged();
    partial void OnEK1_fTChanging(System.Nullable<float> value);
    partial void OnEK1_fTChanged();
    partial void OnEK1_fCChanging(System.Nullable<float> value);
    partial void OnEK1_fCChanged();
    partial void OnEK1_fQmChanging(System.Nullable<float> value);
    partial void OnEK1_fQmChanged();
    partial void OnEK1_fQbChanging(System.Nullable<float> value);
    partial void OnEK1_fQbChanged();
    partial void OnEK1_fTbXChanging(System.Nullable<float> value);
    partial void OnEK1_fTbXChanged();
    partial void OnEK1_fPbXChanging(System.Nullable<float> value);
    partial void OnEK1_fPbXChanged();
    partial void OnEK1_nBatRemainChanging(System.Nullable<int> value);
    partial void OnEK1_nBatRemainChanged();
    partial void OnEK2_nVbChanging(System.Nullable<long> value);
    partial void OnEK2_nVbChanged();
    partial void OnEK2_nVbDChanging(System.Nullable<long> value);
    partial void OnEK2_nVbDChanged();
    partial void OnEK2_nVmChanging(System.Nullable<long> value);
    partial void OnEK2_nVmChanged();
    partial void OnEK2_nVmDChanging(System.Nullable<long> value);
    partial void OnEK2_nVmDChanged();
    partial void OnEK2_fP_PsiChanging(System.Nullable<float> value);
    partial void OnEK2_fP_PsiChanged();
    partial void OnEK2_fTChanging(System.Nullable<float> value);
    partial void OnEK2_fTChanged();
    partial void OnEK2_fCChanging(System.Nullable<float> value);
    partial void OnEK2_fCChanged();
    partial void OnEK2_fQmChanging(System.Nullable<float> value);
    partial void OnEK2_fQmChanged();
    partial void OnEK2_fQbChanging(System.Nullable<float> value);
    partial void OnEK2_fQbChanged();
    partial void OnEK2_fTbXChanging(System.Nullable<float> value);
    partial void OnEK2_fTbXChanged();
    partial void OnEK2_fPbXChanging(System.Nullable<float> value);
    partial void OnEK2_fPbXChanged();
    partial void OnEK2_nBatRemainChanging(System.Nullable<int> value);
    partial void OnEK2_nBatRemainChanged();
    partial void OnEK3_nVbChanging(System.Nullable<long> value);
    partial void OnEK3_nVbChanged();
    partial void OnEK3_nVbDChanging(System.Nullable<long> value);
    partial void OnEK3_nVbDChanged();
    partial void OnEK3_nVmChanging(System.Nullable<long> value);
    partial void OnEK3_nVmChanged();
    partial void OnEK3_nVmDChanging(System.Nullable<long> value);
    partial void OnEK3_nVmDChanged();
    partial void OnEK3_fP_PsiChanging(System.Nullable<float> value);
    partial void OnEK3_fP_PsiChanged();
    partial void OnEK3_fTChanging(System.Nullable<float> value);
    partial void OnEK3_fTChanged();
    partial void OnEK3_fCChanging(System.Nullable<float> value);
    partial void OnEK3_fCChanged();
    partial void OnEK3_fQmChanging(System.Nullable<float> value);
    partial void OnEK3_fQmChanged();
    partial void OnEK3_fQbChanging(System.Nullable<float> value);
    partial void OnEK3_fQbChanged();
    partial void OnEK3_fTbXChanging(System.Nullable<float> value);
    partial void OnEK3_fTbXChanged();
    partial void OnEK3_fPbXChanging(System.Nullable<float> value);
    partial void OnEK3_fPbXChanged();
    partial void OnEK3_nBatRemainChanging(System.Nullable<int> value);
    partial void OnEK3_nBatRemainChanged();
    partial void OnfInT_Ht1Changing(System.Nullable<float> value);
    partial void OnfInT_Ht1Changed();
    partial void OnfOutT_Ht1Changing(System.Nullable<float> value);
    partial void OnfOutT_Ht1Changed();
    partial void OnbWaterLLA_Ht1Changing(System.Nullable<bool> value);
    partial void OnbWaterLLA_Ht1Changed();
    partial void OnfInT_Ht2Changing(System.Nullable<float> value);
    partial void OnfInT_Ht2Changed();
    partial void OnfOutT_Ht2Changing(System.Nullable<float> value);
    partial void OnfOutT_Ht2Changed();
    partial void OnfWaterT_Ht2Changing(System.Nullable<float> value);
    partial void OnfWaterT_Ht2Changed();
    partial void OnbWaterLLA_Ht2Changing(System.Nullable<bool> value);
    partial void OnbWaterLLA_Ht2Changed();
    partial void OnfWaterT_Ht1Changing(System.Nullable<float> value);
    partial void OnfWaterT_Ht1Changed();
    #endregion
		
		public Table_TSample()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationCode", DbType="VarChar(20)")]
		public string GasStationCode
		{
			get
			{
				return this._GasStationCode;
			}
			set
			{
				if ((this._GasStationCode != value))
				{
					this.OnGasStationCodeChanging(value);
					this.SendPropertyChanging();
					this._GasStationCode = value;
					this.SendPropertyChanged("GasStationCode");
					this.OnGasStationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationName", DbType="VarChar(100)")]
		public string GasStationName
		{
			get
			{
				return this._GasStationName;
			}
			set
			{
				if ((this._GasStationName != value))
				{
					this.OnGasStationNameChanging(value);
					this.SendPropertyChanging();
					this._GasStationName = value;
					this.SendPropertyChanged("GasStationName");
					this.OnGasStationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_Stamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> time_Stamp
		{
			get
			{
				return this._time_Stamp;
			}
			set
			{
				if ((this._time_Stamp != value))
				{
					this.Ontime_StampChanging(value);
					this.SendPropertyChanging();
					this._time_Stamp = value;
					this.SendPropertyChanged("time_Stamp");
					this.Ontime_StampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTimeStampShamsi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string strTimeStampShamsi
		{
			get
			{
				return this._strTimeStampShamsi;
			}
			set
			{
				if ((this._strTimeStampShamsi != value))
				{
					this.OnstrTimeStampShamsiChanging(value);
					this.SendPropertyChanging();
					this._strTimeStampShamsi = value;
					this.SendPropertyChanged("strTimeStampShamsi");
					this.OnstrTimeStampShamsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bInvalid", DbType="Bit")]
		public System.Nullable<bool> bInvalid
		{
			get
			{
				return this._bInvalid;
			}
			set
			{
				if ((this._bInvalid != value))
				{
					this.OnbInvalidChanging(value);
					this.SendPropertyChanging();
					this._bInvalid = value;
					this.SendPropertyChanged("bInvalid");
					this.OnbInvalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nStationID", DbType="Int")]
		public System.Nullable<int> nStationID
		{
			get
			{
				return this._nStationID;
			}
			set
			{
				if ((this._nStationID != value))
				{
					this.OnnStationIDChanging(value);
					this.SendPropertyChanging();
					this._nStationID = value;
					this.SendPropertyChanged("nStationID");
					this.OnnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nProjectID", DbType="Int")]
		public System.Nullable<int> nProjectID
		{
			get
			{
				return this._nProjectID;
			}
			set
			{
				if ((this._nProjectID != value))
				{
					this.OnnProjectIDChanging(value);
					this.SendPropertyChanging();
					this._nProjectID = value;
					this.SendPropertyChanged("nProjectID");
					this.OnnProjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSysUpTime_Hour", DbType="Real")]
		public System.Nullable<float> fSysUpTime_Hour
		{
			get
			{
				return this._fSysUpTime_Hour;
			}
			set
			{
				if ((this._fSysUpTime_Hour != value))
				{
					this.OnfSysUpTime_HourChanging(value);
					this.SendPropertyChanging();
					this._fSysUpTime_Hour = value;
					this.SendPropertyChanged("fSysUpTime_Hour");
					this.OnfSysUpTime_HourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nSourceID_OfResetPAC", DbType="Int")]
		public System.Nullable<int> nSourceID_OfResetPAC
		{
			get
			{
				return this._nSourceID_OfResetPAC;
			}
			set
			{
				if ((this._nSourceID_OfResetPAC != value))
				{
					this.OnnSourceID_OfResetPACChanging(value);
					this.SendPropertyChanging();
					this._nSourceID_OfResetPAC = value;
					this.SendPropertyChanged("nSourceID_OfResetPAC");
					this.OnnSourceID_OfResetPACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bResetPAC_Pend", DbType="Bit")]
		public System.Nullable<bool> bResetPAC_Pend
		{
			get
			{
				return this._bResetPAC_Pend;
			}
			set
			{
				if ((this._bResetPAC_Pend != value))
				{
					this.OnbResetPAC_PendChanging(value);
					this.SendPropertyChanging();
					this._bResetPAC_Pend = value;
					this.SendPropertyChanged("bResetPAC_Pend");
					this.OnbResetPAC_PendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fStationCapacity", DbType="Real")]
		public System.Nullable<float> fStationCapacity
		{
			get
			{
				return this._fStationCapacity;
			}
			set
			{
				if ((this._fStationCapacity != value))
				{
					this.OnfStationCapacityChanging(value);
					this.SendPropertyChanging();
					this._fStationCapacity = value;
					this.SendPropertyChanged("fStationCapacity");
					this.OnfStationCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fTotalQb", DbType="Real")]
		public System.Nullable<float> fTotalQb
		{
			get
			{
				return this._fTotalQb;
			}
			set
			{
				if ((this._fTotalQb != value))
				{
					this.OnfTotalQbChanging(value);
					this.SendPropertyChanging();
					this._fTotalQb = value;
					this.SendPropertyChanged("fTotalQb");
					this.OnfTotalQbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fTotalQm", DbType="Real")]
		public System.Nullable<float> fTotalQm
		{
			get
			{
				return this._fTotalQm;
			}
			set
			{
				if ((this._fTotalQm != value))
				{
					this.OnfTotalQmChanging(value);
					this.SendPropertyChanging();
					this._fTotalQm = value;
					this.SendPropertyChanged("fTotalQm");
					this.OnfTotalQmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInGasT", DbType="Real")]
		public System.Nullable<float> fInGasT
		{
			get
			{
				return this._fInGasT;
			}
			set
			{
				if ((this._fInGasT != value))
				{
					this.OnfInGasTChanging(value);
					this.SendPropertyChanging();
					this._fInGasT = value;
					this.SendPropertyChanged("fInGasT");
					this.OnfInGasTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutGasT", DbType="Real")]
		public System.Nullable<float> fOutGasT
		{
			get
			{
				return this._fOutGasT;
			}
			set
			{
				if ((this._fOutGasT != value))
				{
					this.OnfOutGasTChanging(value);
					this.SendPropertyChanging();
					this._fOutGasT = value;
					this.SendPropertyChanged("fOutGasT");
					this.OnfOutGasTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInGasP", DbType="Real")]
		public System.Nullable<float> fInGasP
		{
			get
			{
				return this._fInGasP;
			}
			set
			{
				if ((this._fInGasP != value))
				{
					this.OnfInGasPChanging(value);
					this.SendPropertyChanging();
					this._fInGasP = value;
					this.SendPropertyChanged("fInGasP");
					this.OnfInGasPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutGasP", DbType="Real")]
		public System.Nullable<float> fOutGasP
		{
			get
			{
				return this._fOutGasP;
			}
			set
			{
				if ((this._fOutGasP != value))
				{
					this.OnfOutGasPChanging(value);
					this.SendPropertyChanging();
					this._fOutGasP = value;
					this.SendPropertyChanged("fOutGasP");
					this.OnfOutGasPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAirT", DbType="Real")]
		public System.Nullable<float> fAirT
		{
			get
			{
				return this._fAirT;
			}
			set
			{
				if ((this._fAirT != value))
				{
					this.OnfAirTChanging(value);
					this.SendPropertyChanging();
					this._fAirT = value;
					this.SendPropertyChanged("fAirT");
					this.OnfAirTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVb", DbType="BigInt")]
		public System.Nullable<long> EK1_nVb
		{
			get
			{
				return this._EK1_nVb;
			}
			set
			{
				if ((this._EK1_nVb != value))
				{
					this.OnEK1_nVbChanging(value);
					this.SendPropertyChanging();
					this._EK1_nVb = value;
					this.SendPropertyChanged("EK1_nVb");
					this.OnEK1_nVbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVbD", DbType="BigInt")]
		public System.Nullable<long> EK1_nVbD
		{
			get
			{
				return this._EK1_nVbD;
			}
			set
			{
				if ((this._EK1_nVbD != value))
				{
					this.OnEK1_nVbDChanging(value);
					this.SendPropertyChanging();
					this._EK1_nVbD = value;
					this.SendPropertyChanged("EK1_nVbD");
					this.OnEK1_nVbDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVm", DbType="BigInt")]
		public System.Nullable<long> EK1_nVm
		{
			get
			{
				return this._EK1_nVm;
			}
			set
			{
				if ((this._EK1_nVm != value))
				{
					this.OnEK1_nVmChanging(value);
					this.SendPropertyChanging();
					this._EK1_nVm = value;
					this.SendPropertyChanged("EK1_nVm");
					this.OnEK1_nVmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nVmD", DbType="BigInt")]
		public System.Nullable<long> EK1_nVmD
		{
			get
			{
				return this._EK1_nVmD;
			}
			set
			{
				if ((this._EK1_nVmD != value))
				{
					this.OnEK1_nVmDChanging(value);
					this.SendPropertyChanging();
					this._EK1_nVmD = value;
					this.SendPropertyChanged("EK1_nVmD");
					this.OnEK1_nVmDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fP_Psi", DbType="Real")]
		public System.Nullable<float> EK1_fP_Psi
		{
			get
			{
				return this._EK1_fP_Psi;
			}
			set
			{
				if ((this._EK1_fP_Psi != value))
				{
					this.OnEK1_fP_PsiChanging(value);
					this.SendPropertyChanging();
					this._EK1_fP_Psi = value;
					this.SendPropertyChanged("EK1_fP_Psi");
					this.OnEK1_fP_PsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fT", DbType="Real")]
		public System.Nullable<float> EK1_fT
		{
			get
			{
				return this._EK1_fT;
			}
			set
			{
				if ((this._EK1_fT != value))
				{
					this.OnEK1_fTChanging(value);
					this.SendPropertyChanging();
					this._EK1_fT = value;
					this.SendPropertyChanged("EK1_fT");
					this.OnEK1_fTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fC", DbType="Real")]
		public System.Nullable<float> EK1_fC
		{
			get
			{
				return this._EK1_fC;
			}
			set
			{
				if ((this._EK1_fC != value))
				{
					this.OnEK1_fCChanging(value);
					this.SendPropertyChanging();
					this._EK1_fC = value;
					this.SendPropertyChanged("EK1_fC");
					this.OnEK1_fCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fQm", DbType="Real")]
		public System.Nullable<float> EK1_fQm
		{
			get
			{
				return this._EK1_fQm;
			}
			set
			{
				if ((this._EK1_fQm != value))
				{
					this.OnEK1_fQmChanging(value);
					this.SendPropertyChanging();
					this._EK1_fQm = value;
					this.SendPropertyChanged("EK1_fQm");
					this.OnEK1_fQmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fQb", DbType="Real")]
		public System.Nullable<float> EK1_fQb
		{
			get
			{
				return this._EK1_fQb;
			}
			set
			{
				if ((this._EK1_fQb != value))
				{
					this.OnEK1_fQbChanging(value);
					this.SendPropertyChanging();
					this._EK1_fQb = value;
					this.SendPropertyChanged("EK1_fQb");
					this.OnEK1_fQbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fTbX", DbType="Real")]
		public System.Nullable<float> EK1_fTbX
		{
			get
			{
				return this._EK1_fTbX;
			}
			set
			{
				if ((this._EK1_fTbX != value))
				{
					this.OnEK1_fTbXChanging(value);
					this.SendPropertyChanging();
					this._EK1_fTbX = value;
					this.SendPropertyChanged("EK1_fTbX");
					this.OnEK1_fTbXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_fPbX", DbType="Real")]
		public System.Nullable<float> EK1_fPbX
		{
			get
			{
				return this._EK1_fPbX;
			}
			set
			{
				if ((this._EK1_fPbX != value))
				{
					this.OnEK1_fPbXChanging(value);
					this.SendPropertyChanging();
					this._EK1_fPbX = value;
					this.SendPropertyChanged("EK1_fPbX");
					this.OnEK1_fPbXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK1_nBatRemain", DbType="Int")]
		public System.Nullable<int> EK1_nBatRemain
		{
			get
			{
				return this._EK1_nBatRemain;
			}
			set
			{
				if ((this._EK1_nBatRemain != value))
				{
					this.OnEK1_nBatRemainChanging(value);
					this.SendPropertyChanging();
					this._EK1_nBatRemain = value;
					this.SendPropertyChanged("EK1_nBatRemain");
					this.OnEK1_nBatRemainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVb", DbType="BigInt")]
		public System.Nullable<long> EK2_nVb
		{
			get
			{
				return this._EK2_nVb;
			}
			set
			{
				if ((this._EK2_nVb != value))
				{
					this.OnEK2_nVbChanging(value);
					this.SendPropertyChanging();
					this._EK2_nVb = value;
					this.SendPropertyChanged("EK2_nVb");
					this.OnEK2_nVbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVbD", DbType="BigInt")]
		public System.Nullable<long> EK2_nVbD
		{
			get
			{
				return this._EK2_nVbD;
			}
			set
			{
				if ((this._EK2_nVbD != value))
				{
					this.OnEK2_nVbDChanging(value);
					this.SendPropertyChanging();
					this._EK2_nVbD = value;
					this.SendPropertyChanged("EK2_nVbD");
					this.OnEK2_nVbDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVm", DbType="BigInt")]
		public System.Nullable<long> EK2_nVm
		{
			get
			{
				return this._EK2_nVm;
			}
			set
			{
				if ((this._EK2_nVm != value))
				{
					this.OnEK2_nVmChanging(value);
					this.SendPropertyChanging();
					this._EK2_nVm = value;
					this.SendPropertyChanged("EK2_nVm");
					this.OnEK2_nVmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nVmD", DbType="BigInt")]
		public System.Nullable<long> EK2_nVmD
		{
			get
			{
				return this._EK2_nVmD;
			}
			set
			{
				if ((this._EK2_nVmD != value))
				{
					this.OnEK2_nVmDChanging(value);
					this.SendPropertyChanging();
					this._EK2_nVmD = value;
					this.SendPropertyChanged("EK2_nVmD");
					this.OnEK2_nVmDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fP_Psi", DbType="Real")]
		public System.Nullable<float> EK2_fP_Psi
		{
			get
			{
				return this._EK2_fP_Psi;
			}
			set
			{
				if ((this._EK2_fP_Psi != value))
				{
					this.OnEK2_fP_PsiChanging(value);
					this.SendPropertyChanging();
					this._EK2_fP_Psi = value;
					this.SendPropertyChanged("EK2_fP_Psi");
					this.OnEK2_fP_PsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fT", DbType="Real")]
		public System.Nullable<float> EK2_fT
		{
			get
			{
				return this._EK2_fT;
			}
			set
			{
				if ((this._EK2_fT != value))
				{
					this.OnEK2_fTChanging(value);
					this.SendPropertyChanging();
					this._EK2_fT = value;
					this.SendPropertyChanged("EK2_fT");
					this.OnEK2_fTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fC", DbType="Real")]
		public System.Nullable<float> EK2_fC
		{
			get
			{
				return this._EK2_fC;
			}
			set
			{
				if ((this._EK2_fC != value))
				{
					this.OnEK2_fCChanging(value);
					this.SendPropertyChanging();
					this._EK2_fC = value;
					this.SendPropertyChanged("EK2_fC");
					this.OnEK2_fCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fQm", DbType="Real")]
		public System.Nullable<float> EK2_fQm
		{
			get
			{
				return this._EK2_fQm;
			}
			set
			{
				if ((this._EK2_fQm != value))
				{
					this.OnEK2_fQmChanging(value);
					this.SendPropertyChanging();
					this._EK2_fQm = value;
					this.SendPropertyChanged("EK2_fQm");
					this.OnEK2_fQmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fQb", DbType="Real")]
		public System.Nullable<float> EK2_fQb
		{
			get
			{
				return this._EK2_fQb;
			}
			set
			{
				if ((this._EK2_fQb != value))
				{
					this.OnEK2_fQbChanging(value);
					this.SendPropertyChanging();
					this._EK2_fQb = value;
					this.SendPropertyChanged("EK2_fQb");
					this.OnEK2_fQbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fTbX", DbType="Real")]
		public System.Nullable<float> EK2_fTbX
		{
			get
			{
				return this._EK2_fTbX;
			}
			set
			{
				if ((this._EK2_fTbX != value))
				{
					this.OnEK2_fTbXChanging(value);
					this.SendPropertyChanging();
					this._EK2_fTbX = value;
					this.SendPropertyChanged("EK2_fTbX");
					this.OnEK2_fTbXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_fPbX", DbType="Real")]
		public System.Nullable<float> EK2_fPbX
		{
			get
			{
				return this._EK2_fPbX;
			}
			set
			{
				if ((this._EK2_fPbX != value))
				{
					this.OnEK2_fPbXChanging(value);
					this.SendPropertyChanging();
					this._EK2_fPbX = value;
					this.SendPropertyChanged("EK2_fPbX");
					this.OnEK2_fPbXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK2_nBatRemain", DbType="Int")]
		public System.Nullable<int> EK2_nBatRemain
		{
			get
			{
				return this._EK2_nBatRemain;
			}
			set
			{
				if ((this._EK2_nBatRemain != value))
				{
					this.OnEK2_nBatRemainChanging(value);
					this.SendPropertyChanging();
					this._EK2_nBatRemain = value;
					this.SendPropertyChanged("EK2_nBatRemain");
					this.OnEK2_nBatRemainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVb", DbType="BigInt")]
		public System.Nullable<long> EK3_nVb
		{
			get
			{
				return this._EK3_nVb;
			}
			set
			{
				if ((this._EK3_nVb != value))
				{
					this.OnEK3_nVbChanging(value);
					this.SendPropertyChanging();
					this._EK3_nVb = value;
					this.SendPropertyChanged("EK3_nVb");
					this.OnEK3_nVbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVbD", DbType="BigInt")]
		public System.Nullable<long> EK3_nVbD
		{
			get
			{
				return this._EK3_nVbD;
			}
			set
			{
				if ((this._EK3_nVbD != value))
				{
					this.OnEK3_nVbDChanging(value);
					this.SendPropertyChanging();
					this._EK3_nVbD = value;
					this.SendPropertyChanged("EK3_nVbD");
					this.OnEK3_nVbDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVm", DbType="BigInt")]
		public System.Nullable<long> EK3_nVm
		{
			get
			{
				return this._EK3_nVm;
			}
			set
			{
				if ((this._EK3_nVm != value))
				{
					this.OnEK3_nVmChanging(value);
					this.SendPropertyChanging();
					this._EK3_nVm = value;
					this.SendPropertyChanged("EK3_nVm");
					this.OnEK3_nVmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nVmD", DbType="BigInt")]
		public System.Nullable<long> EK3_nVmD
		{
			get
			{
				return this._EK3_nVmD;
			}
			set
			{
				if ((this._EK3_nVmD != value))
				{
					this.OnEK3_nVmDChanging(value);
					this.SendPropertyChanging();
					this._EK3_nVmD = value;
					this.SendPropertyChanged("EK3_nVmD");
					this.OnEK3_nVmDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fP_Psi", DbType="Real")]
		public System.Nullable<float> EK3_fP_Psi
		{
			get
			{
				return this._EK3_fP_Psi;
			}
			set
			{
				if ((this._EK3_fP_Psi != value))
				{
					this.OnEK3_fP_PsiChanging(value);
					this.SendPropertyChanging();
					this._EK3_fP_Psi = value;
					this.SendPropertyChanged("EK3_fP_Psi");
					this.OnEK3_fP_PsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fT", DbType="Real")]
		public System.Nullable<float> EK3_fT
		{
			get
			{
				return this._EK3_fT;
			}
			set
			{
				if ((this._EK3_fT != value))
				{
					this.OnEK3_fTChanging(value);
					this.SendPropertyChanging();
					this._EK3_fT = value;
					this.SendPropertyChanged("EK3_fT");
					this.OnEK3_fTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fC", DbType="Real")]
		public System.Nullable<float> EK3_fC
		{
			get
			{
				return this._EK3_fC;
			}
			set
			{
				if ((this._EK3_fC != value))
				{
					this.OnEK3_fCChanging(value);
					this.SendPropertyChanging();
					this._EK3_fC = value;
					this.SendPropertyChanged("EK3_fC");
					this.OnEK3_fCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fQm", DbType="Real")]
		public System.Nullable<float> EK3_fQm
		{
			get
			{
				return this._EK3_fQm;
			}
			set
			{
				if ((this._EK3_fQm != value))
				{
					this.OnEK3_fQmChanging(value);
					this.SendPropertyChanging();
					this._EK3_fQm = value;
					this.SendPropertyChanged("EK3_fQm");
					this.OnEK3_fQmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fQb", DbType="Real")]
		public System.Nullable<float> EK3_fQb
		{
			get
			{
				return this._EK3_fQb;
			}
			set
			{
				if ((this._EK3_fQb != value))
				{
					this.OnEK3_fQbChanging(value);
					this.SendPropertyChanging();
					this._EK3_fQb = value;
					this.SendPropertyChanged("EK3_fQb");
					this.OnEK3_fQbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fTbX", DbType="Real")]
		public System.Nullable<float> EK3_fTbX
		{
			get
			{
				return this._EK3_fTbX;
			}
			set
			{
				if ((this._EK3_fTbX != value))
				{
					this.OnEK3_fTbXChanging(value);
					this.SendPropertyChanging();
					this._EK3_fTbX = value;
					this.SendPropertyChanged("EK3_fTbX");
					this.OnEK3_fTbXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_fPbX", DbType="Real")]
		public System.Nullable<float> EK3_fPbX
		{
			get
			{
				return this._EK3_fPbX;
			}
			set
			{
				if ((this._EK3_fPbX != value))
				{
					this.OnEK3_fPbXChanging(value);
					this.SendPropertyChanging();
					this._EK3_fPbX = value;
					this.SendPropertyChanged("EK3_fPbX");
					this.OnEK3_fPbXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK3_nBatRemain", DbType="Int")]
		public System.Nullable<int> EK3_nBatRemain
		{
			get
			{
				return this._EK3_nBatRemain;
			}
			set
			{
				if ((this._EK3_nBatRemain != value))
				{
					this.OnEK3_nBatRemainChanging(value);
					this.SendPropertyChanging();
					this._EK3_nBatRemain = value;
					this.SendPropertyChanged("EK3_nBatRemain");
					this.OnEK3_nBatRemainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInT_Ht1", DbType="Real")]
		public System.Nullable<float> fInT_Ht1
		{
			get
			{
				return this._fInT_Ht1;
			}
			set
			{
				if ((this._fInT_Ht1 != value))
				{
					this.OnfInT_Ht1Changing(value);
					this.SendPropertyChanging();
					this._fInT_Ht1 = value;
					this.SendPropertyChanged("fInT_Ht1");
					this.OnfInT_Ht1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutT_Ht1", DbType="Real")]
		public System.Nullable<float> fOutT_Ht1
		{
			get
			{
				return this._fOutT_Ht1;
			}
			set
			{
				if ((this._fOutT_Ht1 != value))
				{
					this.OnfOutT_Ht1Changing(value);
					this.SendPropertyChanging();
					this._fOutT_Ht1 = value;
					this.SendPropertyChanged("fOutT_Ht1");
					this.OnfOutT_Ht1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bWaterLLA_Ht1", DbType="Bit")]
		public System.Nullable<bool> bWaterLLA_Ht1
		{
			get
			{
				return this._bWaterLLA_Ht1;
			}
			set
			{
				if ((this._bWaterLLA_Ht1 != value))
				{
					this.OnbWaterLLA_Ht1Changing(value);
					this.SendPropertyChanging();
					this._bWaterLLA_Ht1 = value;
					this.SendPropertyChanged("bWaterLLA_Ht1");
					this.OnbWaterLLA_Ht1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInT_Ht2", DbType="Real")]
		public System.Nullable<float> fInT_Ht2
		{
			get
			{
				return this._fInT_Ht2;
			}
			set
			{
				if ((this._fInT_Ht2 != value))
				{
					this.OnfInT_Ht2Changing(value);
					this.SendPropertyChanging();
					this._fInT_Ht2 = value;
					this.SendPropertyChanged("fInT_Ht2");
					this.OnfInT_Ht2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOutT_Ht2", DbType="Real")]
		public System.Nullable<float> fOutT_Ht2
		{
			get
			{
				return this._fOutT_Ht2;
			}
			set
			{
				if ((this._fOutT_Ht2 != value))
				{
					this.OnfOutT_Ht2Changing(value);
					this.SendPropertyChanging();
					this._fOutT_Ht2 = value;
					this.SendPropertyChanged("fOutT_Ht2");
					this.OnfOutT_Ht2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fWaterT_Ht2", DbType="Real")]
		public System.Nullable<float> fWaterT_Ht2
		{
			get
			{
				return this._fWaterT_Ht2;
			}
			set
			{
				if ((this._fWaterT_Ht2 != value))
				{
					this.OnfWaterT_Ht2Changing(value);
					this.SendPropertyChanging();
					this._fWaterT_Ht2 = value;
					this.SendPropertyChanged("fWaterT_Ht2");
					this.OnfWaterT_Ht2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bWaterLLA_Ht2", DbType="Bit")]
		public System.Nullable<bool> bWaterLLA_Ht2
		{
			get
			{
				return this._bWaterLLA_Ht2;
			}
			set
			{
				if ((this._bWaterLLA_Ht2 != value))
				{
					this.OnbWaterLLA_Ht2Changing(value);
					this.SendPropertyChanging();
					this._bWaterLLA_Ht2 = value;
					this.SendPropertyChanged("bWaterLLA_Ht2");
					this.OnbWaterLLA_Ht2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fWaterT_Ht1", DbType="Real")]
		public System.Nullable<float> fWaterT_Ht1
		{
			get
			{
				return this._fWaterT_Ht1;
			}
			set
			{
				if ((this._fWaterT_Ht1 != value))
				{
					this.OnfWaterT_Ht1Changing(value);
					this.SendPropertyChanging();
					this._fWaterT_Ht1 = value;
					this.SendPropertyChanged("fWaterT_Ht1");
					this.OnfWaterT_Ht1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
