<?xml version="1.0" encoding="utf-8"?><Database Name="GasStationManagement" Class="DataClassesTemGageSupplyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=GasStationManagement;Integrated Security=True" SettingsObjectName="GasStationManagement.Model.Properties.Settings" SettingsPropertyName="GasStationManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_TemGageSupply" Member="TBL_TemGageSupplies">
    <Type Name="TBL_TemGageSupply">
      <Column Name="TemGage_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TemGageSerialNo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SupplyDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Suppliers_Id" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_TemGageSupply" Member="VW_TemGageSupplies">
    <Type Name="VW_TemGageSupply">
      <Column Name="TemGage_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TemGageSerialNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupplyDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Suppliers_Id" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GageSize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PacketLength" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TMin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TMax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CalibrationDuration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SP_TemGageSupplyDelete" Method="SP_TemGageSupplyDelete">
    <Parameter Name="TemGage_Id" Parameter="temGage_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="TemGageSerialNo" Parameter="temGageSerialNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(2000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_TemGageSupplyInsert" Method="SP_TemGageSupplyInsert">
    <Parameter Name="TemGage_Id" Parameter="temGage_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="TemGageSerialNo" Parameter="temGageSerialNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SupplyDate" Parameter="supplyDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Price" Parameter="price" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Suppliers_Id" Parameter="suppliers_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(4000)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_TemGageSupplyUpdate" Method="SP_TemGageSupplyUpdate">
    <Parameter Name="TemGage_Id" Parameter="temGage_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="TemGageSerialNo" Parameter="temGageSerialNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SupplyDate" Parameter="supplyDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Price" Parameter="price" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Suppliers_Id" Parameter="suppliers_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(4000)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>