#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationManagement.Model.GasStation
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GasStationManagement")]
	public partial class DataClassesGasStationsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGasStation(GasStation instance);
    partial void UpdateGasStation(GasStation instance);
    partial void DeleteGasStation(GasStation instance);
    #endregion
		
		public DataClassesGasStationsDataContext() : 
				base(global::GasStationManagement.Model.Properties.Settings.Default.GasStationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGasStationsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGasStationsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGasStationsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGasStationsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GasStation> GasStations
		{
			get
			{
				return this.GetTable<GasStation>();
			}
		}
		
		public System.Data.Linq.Table<VW_GasStation> VW_GasStations
		{
			get
			{
				return this.GetTable<VW_GasStation>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GasStationCreateTable")]
		public int SP_GasStationCreateTable([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationCode", DbType="VarChar(20)")] string gasStationCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gasStationCode, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GasStationsDelete")]
		public int SP_GasStationsDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GasStationsInsert")]
		public int SP_GasStationsInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationCode", DbType="VarChar(20)")] string gasStationCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationName", DbType="VarChar(100)")] string gasStationName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationBuildingDate", DbType="VarChar(10)")] string gasStationBuildingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Capacity", DbType="Int")] System.Nullable<int> capacity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationType_Id", DbType="SmallInt")] System.Nullable<short> gasStationType_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WorkingPressure_Id", DbType="SmallInt")] System.Nullable<short> workingPressure_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseType_Id", DbType="SmallInt")] System.Nullable<short> useType_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ScheduleRegInfo", DbType="SmallInt")] System.Nullable<short> scheduleRegInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ScheduleSpecPeriod", DbType="Int")] System.Nullable<int> scheduleSpecPeriod, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Line_Id", DbType="SmallInt")] System.Nullable<short> line_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStation_Id", DbType="Int")] System.Nullable<int> gasStation_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RanFew", DbType="Int")] System.Nullable<int> ranFew, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Heater_Few", DbType="Int")] System.Nullable<int> heater_Few, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CounterInsLoc_Id", DbType="SmallInt")] System.Nullable<short> counterInsLoc_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrectionFactor", DbType="Int")] System.Nullable<int> correctionFactor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StationLinkType_Id", DbType="SmallInt")] System.Nullable<short> stationLinkType_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysState_Id", DbType="SmallInt")] System.Nullable<short> monitoringSysState_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysExeDate", DbType="VarChar(10)")] string monitoringSysExeDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, gasStationCode, gasStationName, gasStationBuildingDate, capacity, gasStationType_Id, workingPressure_Id, useType_Id, scheduleRegInfo, scheduleSpecPeriod, line_Id, gasStation_Id, ranFew, heater_Few, counterInsLoc_Id, correctionFactor, stationLinkType_Id, monitoringSysState_Id, monitoringSysExeDate, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(22)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GasStationsUpdate")]
		public int SP_GasStationsUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationCode", DbType="VarChar(20)")] string gasStationCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationName", DbType="VarChar(100)")] string gasStationName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationBuildingDate", DbType="VarChar(10)")] string gasStationBuildingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Capacity", DbType="Int")] System.Nullable<int> capacity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStationType_Id", DbType="SmallInt")] System.Nullable<short> gasStationType_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WorkingPressure_Id", DbType="SmallInt")] System.Nullable<short> workingPressure_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseType_Id", DbType="SmallInt")] System.Nullable<short> useType_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ScheduleRegInfo", DbType="SmallInt")] System.Nullable<short> scheduleRegInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ScheduleSpecPeriod", DbType="Int")] System.Nullable<int> scheduleSpecPeriod, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Line_Id", DbType="SmallInt")] System.Nullable<short> line_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GasStation_Id", DbType="Int")] System.Nullable<int> gasStation_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RanFew", DbType="Int")] System.Nullable<int> ranFew, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Heater_Few", DbType="Int")] System.Nullable<int> heater_Few, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CounterInsLoc_Id", DbType="SmallInt")] System.Nullable<short> counterInsLoc_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrectionFactor", DbType="Int")] System.Nullable<int> correctionFactor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StationLinkType_Id", DbType="SmallInt")] System.Nullable<short> stationLinkType_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysState_Id", DbType="SmallInt")] System.Nullable<short> monitoringSysState_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonitoringSysExeDate", DbType="VarChar(10)")] string monitoringSysExeDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suppliers_Id", DbType="SmallInt")] System.Nullable<short> suppliers_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(4000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, gasStationCode, gasStationName, gasStationBuildingDate, capacity, gasStationType_Id, workingPressure_Id, useType_Id, scheduleRegInfo, scheduleSpecPeriod, line_Id, gasStation_Id, ranFew, heater_Few, counterInsLoc_Id, correctionFactor, stationLinkType_Id, monitoringSysState_Id, monitoringSysExeDate, suppliers_Id, description, isActive, msgRet);
			msgRet = ((string)(result.GetParameterValue(22)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GasStations")]
	public partial class GasStation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GasStationCode;
		
		private string _GasStationName;
		
		private string _GasStationBuildingDate;
		
		private int _Capacity;
		
		private short _GasStationType_Id;
		
		private short _WorkingPressure_Id;
		
		private short _UseType_Id;
		
		private short _ScheduleRegInfo;
		
		private System.Nullable<int> _ScheduleSpecPeriod;
		
		private System.Nullable<short> _Line_Id;
		
		private System.Nullable<int> _GasStation_Id;
		
		private int _RanFew;
		
		private System.Nullable<int> _Heater_Few;
		
		private short _CounterInsLoc_Id;
		
		private System.Nullable<int> _CorrectionFactor;
		
		private System.Nullable<short> _StationLinkType_Id;
		
		private System.Nullable<short> _MonitoringSysState_Id;
		
		private string _MonitoringSysExeDate;
		
		private System.Nullable<short> _Suppliers_Id;
		
		private string _Description;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGasStationCodeChanging(string value);
    partial void OnGasStationCodeChanged();
    partial void OnGasStationNameChanging(string value);
    partial void OnGasStationNameChanged();
    partial void OnGasStationBuildingDateChanging(string value);
    partial void OnGasStationBuildingDateChanged();
    partial void OnCapacityChanging(int value);
    partial void OnCapacityChanged();
    partial void OnGasStationType_IdChanging(short value);
    partial void OnGasStationType_IdChanged();
    partial void OnWorkingPressure_IdChanging(short value);
    partial void OnWorkingPressure_IdChanged();
    partial void OnUseType_IdChanging(short value);
    partial void OnUseType_IdChanged();
    partial void OnScheduleRegInfoChanging(short value);
    partial void OnScheduleRegInfoChanged();
    partial void OnScheduleSpecPeriodChanging(System.Nullable<int> value);
    partial void OnScheduleSpecPeriodChanged();
    partial void OnLine_IdChanging(System.Nullable<short> value);
    partial void OnLine_IdChanged();
    partial void OnGasStation_IdChanging(System.Nullable<int> value);
    partial void OnGasStation_IdChanged();
    partial void OnRanFewChanging(int value);
    partial void OnRanFewChanged();
    partial void OnHeater_FewChanging(System.Nullable<int> value);
    partial void OnHeater_FewChanged();
    partial void OnCounterInsLoc_IdChanging(short value);
    partial void OnCounterInsLoc_IdChanged();
    partial void OnCorrectionFactorChanging(System.Nullable<int> value);
    partial void OnCorrectionFactorChanged();
    partial void OnStationLinkType_IdChanging(System.Nullable<short> value);
    partial void OnStationLinkType_IdChanged();
    partial void OnMonitoringSysState_IdChanging(System.Nullable<short> value);
    partial void OnMonitoringSysState_IdChanged();
    partial void OnMonitoringSysExeDateChanging(string value);
    partial void OnMonitoringSysExeDateChanged();
    partial void OnSuppliers_IdChanging(System.Nullable<short> value);
    partial void OnSuppliers_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public GasStation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GasStationCode
		{
			get
			{
				return this._GasStationCode;
			}
			set
			{
				if ((this._GasStationCode != value))
				{
					this.OnGasStationCodeChanging(value);
					this.SendPropertyChanging();
					this._GasStationCode = value;
					this.SendPropertyChanged("GasStationCode");
					this.OnGasStationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GasStationName
		{
			get
			{
				return this._GasStationName;
			}
			set
			{
				if ((this._GasStationName != value))
				{
					this.OnGasStationNameChanging(value);
					this.SendPropertyChanging();
					this._GasStationName = value;
					this.SendPropertyChanged("GasStationName");
					this.OnGasStationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationBuildingDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GasStationBuildingDate
		{
			get
			{
				return this._GasStationBuildingDate;
			}
			set
			{
				if ((this._GasStationBuildingDate != value))
				{
					this.OnGasStationBuildingDateChanging(value);
					this.SendPropertyChanging();
					this._GasStationBuildingDate = value;
					this.SendPropertyChanged("GasStationBuildingDate");
					this.OnGasStationBuildingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Int NOT NULL")]
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this.OnCapacityChanging(value);
					this.SendPropertyChanging();
					this._Capacity = value;
					this.SendPropertyChanged("Capacity");
					this.OnCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationType_Id", DbType="SmallInt NOT NULL")]
		public short GasStationType_Id
		{
			get
			{
				return this._GasStationType_Id;
			}
			set
			{
				if ((this._GasStationType_Id != value))
				{
					this.OnGasStationType_IdChanging(value);
					this.SendPropertyChanging();
					this._GasStationType_Id = value;
					this.SendPropertyChanged("GasStationType_Id");
					this.OnGasStationType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkingPressure_Id", DbType="SmallInt NOT NULL")]
		public short WorkingPressure_Id
		{
			get
			{
				return this._WorkingPressure_Id;
			}
			set
			{
				if ((this._WorkingPressure_Id != value))
				{
					this.OnWorkingPressure_IdChanging(value);
					this.SendPropertyChanging();
					this._WorkingPressure_Id = value;
					this.SendPropertyChanged("WorkingPressure_Id");
					this.OnWorkingPressure_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseType_Id", DbType="SmallInt NOT NULL")]
		public short UseType_Id
		{
			get
			{
				return this._UseType_Id;
			}
			set
			{
				if ((this._UseType_Id != value))
				{
					this.OnUseType_IdChanging(value);
					this.SendPropertyChanging();
					this._UseType_Id = value;
					this.SendPropertyChanged("UseType_Id");
					this.OnUseType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleRegInfo", DbType="SmallInt NOT NULL")]
		public short ScheduleRegInfo
		{
			get
			{
				return this._ScheduleRegInfo;
			}
			set
			{
				if ((this._ScheduleRegInfo != value))
				{
					this.OnScheduleRegInfoChanging(value);
					this.SendPropertyChanging();
					this._ScheduleRegInfo = value;
					this.SendPropertyChanged("ScheduleRegInfo");
					this.OnScheduleRegInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleSpecPeriod", DbType="Int")]
		public System.Nullable<int> ScheduleSpecPeriod
		{
			get
			{
				return this._ScheduleSpecPeriod;
			}
			set
			{
				if ((this._ScheduleSpecPeriod != value))
				{
					this.OnScheduleSpecPeriodChanging(value);
					this.SendPropertyChanging();
					this._ScheduleSpecPeriod = value;
					this.SendPropertyChanged("ScheduleSpecPeriod");
					this.OnScheduleSpecPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_Id", DbType="SmallInt")]
		public System.Nullable<short> Line_Id
		{
			get
			{
				return this._Line_Id;
			}
			set
			{
				if ((this._Line_Id != value))
				{
					this.OnLine_IdChanging(value);
					this.SendPropertyChanging();
					this._Line_Id = value;
					this.SendPropertyChanged("Line_Id");
					this.OnLine_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStation_Id", DbType="Int")]
		public System.Nullable<int> GasStation_Id
		{
			get
			{
				return this._GasStation_Id;
			}
			set
			{
				if ((this._GasStation_Id != value))
				{
					this.OnGasStation_IdChanging(value);
					this.SendPropertyChanging();
					this._GasStation_Id = value;
					this.SendPropertyChanged("GasStation_Id");
					this.OnGasStation_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanFew", DbType="Int NOT NULL")]
		public int RanFew
		{
			get
			{
				return this._RanFew;
			}
			set
			{
				if ((this._RanFew != value))
				{
					this.OnRanFewChanging(value);
					this.SendPropertyChanging();
					this._RanFew = value;
					this.SendPropertyChanged("RanFew");
					this.OnRanFewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heater_Few", DbType="Int")]
		public System.Nullable<int> Heater_Few
		{
			get
			{
				return this._Heater_Few;
			}
			set
			{
				if ((this._Heater_Few != value))
				{
					this.OnHeater_FewChanging(value);
					this.SendPropertyChanging();
					this._Heater_Few = value;
					this.SendPropertyChanged("Heater_Few");
					this.OnHeater_FewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterInsLoc_Id", DbType="SmallInt NOT NULL")]
		public short CounterInsLoc_Id
		{
			get
			{
				return this._CounterInsLoc_Id;
			}
			set
			{
				if ((this._CounterInsLoc_Id != value))
				{
					this.OnCounterInsLoc_IdChanging(value);
					this.SendPropertyChanging();
					this._CounterInsLoc_Id = value;
					this.SendPropertyChanged("CounterInsLoc_Id");
					this.OnCounterInsLoc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrectionFactor", DbType="Int")]
		public System.Nullable<int> CorrectionFactor
		{
			get
			{
				return this._CorrectionFactor;
			}
			set
			{
				if ((this._CorrectionFactor != value))
				{
					this.OnCorrectionFactorChanging(value);
					this.SendPropertyChanging();
					this._CorrectionFactor = value;
					this.SendPropertyChanged("CorrectionFactor");
					this.OnCorrectionFactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationLinkType_Id", DbType="SmallInt")]
		public System.Nullable<short> StationLinkType_Id
		{
			get
			{
				return this._StationLinkType_Id;
			}
			set
			{
				if ((this._StationLinkType_Id != value))
				{
					this.OnStationLinkType_IdChanging(value);
					this.SendPropertyChanging();
					this._StationLinkType_Id = value;
					this.SendPropertyChanged("StationLinkType_Id");
					this.OnStationLinkType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysState_Id", DbType="SmallInt")]
		public System.Nullable<short> MonitoringSysState_Id
		{
			get
			{
				return this._MonitoringSysState_Id;
			}
			set
			{
				if ((this._MonitoringSysState_Id != value))
				{
					this.OnMonitoringSysState_IdChanging(value);
					this.SendPropertyChanging();
					this._MonitoringSysState_Id = value;
					this.SendPropertyChanged("MonitoringSysState_Id");
					this.OnMonitoringSysState_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysExeDate", DbType="VarChar(10)")]
		public string MonitoringSysExeDate
		{
			get
			{
				return this._MonitoringSysExeDate;
			}
			set
			{
				if ((this._MonitoringSysExeDate != value))
				{
					this.OnMonitoringSysExeDateChanging(value);
					this.SendPropertyChanging();
					this._MonitoringSysExeDate = value;
					this.SendPropertyChanged("MonitoringSysExeDate");
					this.OnMonitoringSysExeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt")]
		public System.Nullable<short> Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this.OnSuppliers_IdChanging(value);
					this.SendPropertyChanging();
					this._Suppliers_Id = value;
					this.SendPropertyChanged("Suppliers_Id");
					this.OnSuppliers_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_GasStations")]
	public partial class VW_GasStation
	{
		
		private int _ID;
		
		private string _GasStationCode;
		
		private string _GasStationName;
		
		private string _GasStationBuildingDate;
		
		private int _Capacity;
		
		private short _GasStationType_Id;
		
		private short _WorkingPressure_Id;
		
		private short _UseType_Id;
		
		private string _ScheduleRegInfoStr;
		
		private short _ScheduleRegInfo;
		
		private System.Nullable<int> _ScheduleSpecPeriod;
		
		private System.Nullable<short> _Line_Id;
		
		private System.Nullable<int> _GasStation_Id;
		
		private int _RanFew;
		
		private System.Nullable<int> _Heater_Few;
		
		private System.Nullable<int> _CorrectionFactor;
		
		private System.Nullable<short> _StationLinkType_Id;
		
		private System.Nullable<short> _MonitoringSysState_Id;
		
		private string _MonitoringSysExeDate;
		
		private System.Nullable<short> _Suppliers_Id;
		
		private string _Description;
		
		private bool _IsActive;
		
		private string _GasStationTypeName;
		
		private string _WorkingPressureName;
		
		private string _UseTypeName;
		
		private string _LineName;
		
		private string _CounterInsLocName;
		
		private string _StationLinkTypeName;
		
		private string _MonitoringSysStateName;
		
		private string _SupplierName;
		
		private string _SupplierAddress;
		
		private string _SupplierTel;
		
		private string _GasStationsOtherCode;
		
		private string _GasStationsOtherName;
		
		private short _CounterInsLoc_Id;
		
		public VW_GasStation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GasStationCode
		{
			get
			{
				return this._GasStationCode;
			}
			set
			{
				if ((this._GasStationCode != value))
				{
					this._GasStationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GasStationName
		{
			get
			{
				return this._GasStationName;
			}
			set
			{
				if ((this._GasStationName != value))
				{
					this._GasStationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationBuildingDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GasStationBuildingDate
		{
			get
			{
				return this._GasStationBuildingDate;
			}
			set
			{
				if ((this._GasStationBuildingDate != value))
				{
					this._GasStationBuildingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Int NOT NULL")]
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this._Capacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationType_Id", DbType="SmallInt NOT NULL")]
		public short GasStationType_Id
		{
			get
			{
				return this._GasStationType_Id;
			}
			set
			{
				if ((this._GasStationType_Id != value))
				{
					this._GasStationType_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkingPressure_Id", DbType="SmallInt NOT NULL")]
		public short WorkingPressure_Id
		{
			get
			{
				return this._WorkingPressure_Id;
			}
			set
			{
				if ((this._WorkingPressure_Id != value))
				{
					this._WorkingPressure_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseType_Id", DbType="SmallInt NOT NULL")]
		public short UseType_Id
		{
			get
			{
				return this._UseType_Id;
			}
			set
			{
				if ((this._UseType_Id != value))
				{
					this._UseType_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleRegInfoStr", DbType="VarChar(8)")]
		public string ScheduleRegInfoStr
		{
			get
			{
				return this._ScheduleRegInfoStr;
			}
			set
			{
				if ((this._ScheduleRegInfoStr != value))
				{
					this._ScheduleRegInfoStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleRegInfo", DbType="SmallInt NOT NULL")]
		public short ScheduleRegInfo
		{
			get
			{
				return this._ScheduleRegInfo;
			}
			set
			{
				if ((this._ScheduleRegInfo != value))
				{
					this._ScheduleRegInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleSpecPeriod", DbType="Int")]
		public System.Nullable<int> ScheduleSpecPeriod
		{
			get
			{
				return this._ScheduleSpecPeriod;
			}
			set
			{
				if ((this._ScheduleSpecPeriod != value))
				{
					this._ScheduleSpecPeriod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_Id", DbType="SmallInt")]
		public System.Nullable<short> Line_Id
		{
			get
			{
				return this._Line_Id;
			}
			set
			{
				if ((this._Line_Id != value))
				{
					this._Line_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStation_Id", DbType="Int")]
		public System.Nullable<int> GasStation_Id
		{
			get
			{
				return this._GasStation_Id;
			}
			set
			{
				if ((this._GasStation_Id != value))
				{
					this._GasStation_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanFew", DbType="Int NOT NULL")]
		public int RanFew
		{
			get
			{
				return this._RanFew;
			}
			set
			{
				if ((this._RanFew != value))
				{
					this._RanFew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heater_Few", DbType="Int")]
		public System.Nullable<int> Heater_Few
		{
			get
			{
				return this._Heater_Few;
			}
			set
			{
				if ((this._Heater_Few != value))
				{
					this._Heater_Few = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrectionFactor", DbType="Int")]
		public System.Nullable<int> CorrectionFactor
		{
			get
			{
				return this._CorrectionFactor;
			}
			set
			{
				if ((this._CorrectionFactor != value))
				{
					this._CorrectionFactor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationLinkType_Id", DbType="SmallInt")]
		public System.Nullable<short> StationLinkType_Id
		{
			get
			{
				return this._StationLinkType_Id;
			}
			set
			{
				if ((this._StationLinkType_Id != value))
				{
					this._StationLinkType_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysState_Id", DbType="SmallInt")]
		public System.Nullable<short> MonitoringSysState_Id
		{
			get
			{
				return this._MonitoringSysState_Id;
			}
			set
			{
				if ((this._MonitoringSysState_Id != value))
				{
					this._MonitoringSysState_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysExeDate", DbType="VarChar(10)")]
		public string MonitoringSysExeDate
		{
			get
			{
				return this._MonitoringSysExeDate;
			}
			set
			{
				if ((this._MonitoringSysExeDate != value))
				{
					this._MonitoringSysExeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suppliers_Id", DbType="SmallInt")]
		public System.Nullable<short> Suppliers_Id
		{
			get
			{
				return this._Suppliers_Id;
			}
			set
			{
				if ((this._Suppliers_Id != value))
				{
					this._Suppliers_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationTypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GasStationTypeName
		{
			get
			{
				return this._GasStationTypeName;
			}
			set
			{
				if ((this._GasStationTypeName != value))
				{
					this._GasStationTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkingPressureName", DbType="VarChar(50)")]
		public string WorkingPressureName
		{
			get
			{
				return this._WorkingPressureName;
			}
			set
			{
				if ((this._WorkingPressureName != value))
				{
					this._WorkingPressureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseTypeName", DbType="VarChar(50)")]
		public string UseTypeName
		{
			get
			{
				return this._UseTypeName;
			}
			set
			{
				if ((this._UseTypeName != value))
				{
					this._UseTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineName", DbType="VarChar(50)")]
		public string LineName
		{
			get
			{
				return this._LineName;
			}
			set
			{
				if ((this._LineName != value))
				{
					this._LineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterInsLocName", DbType="VarChar(50)")]
		public string CounterInsLocName
		{
			get
			{
				return this._CounterInsLocName;
			}
			set
			{
				if ((this._CounterInsLocName != value))
				{
					this._CounterInsLocName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationLinkTypeName", DbType="VarChar(50)")]
		public string StationLinkTypeName
		{
			get
			{
				return this._StationLinkTypeName;
			}
			set
			{
				if ((this._StationLinkTypeName != value))
				{
					this._StationLinkTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoringSysStateName", DbType="VarChar(50)")]
		public string MonitoringSysStateName
		{
			get
			{
				return this._MonitoringSysStateName;
			}
			set
			{
				if ((this._MonitoringSysStateName != value))
				{
					this._MonitoringSysStateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="VarChar(50)")]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierAddress", DbType="VarChar(500)")]
		public string SupplierAddress
		{
			get
			{
				return this._SupplierAddress;
			}
			set
			{
				if ((this._SupplierAddress != value))
				{
					this._SupplierAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierTel", DbType="VarChar(50)")]
		public string SupplierTel
		{
			get
			{
				return this._SupplierTel;
			}
			set
			{
				if ((this._SupplierTel != value))
				{
					this._SupplierTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationsOtherCode", DbType="VarChar(20)")]
		public string GasStationsOtherCode
		{
			get
			{
				return this._GasStationsOtherCode;
			}
			set
			{
				if ((this._GasStationsOtherCode != value))
				{
					this._GasStationsOtherCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasStationsOtherName", DbType="VarChar(100)")]
		public string GasStationsOtherName
		{
			get
			{
				return this._GasStationsOtherName;
			}
			set
			{
				if ((this._GasStationsOtherName != value))
				{
					this._GasStationsOtherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CounterInsLoc_Id", DbType="SmallInt NOT NULL")]
		public short CounterInsLoc_Id
		{
			get
			{
				return this._CounterInsLoc_Id;
			}
			set
			{
				if ((this._CounterInsLoc_Id != value))
				{
					this._CounterInsLoc_Id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
